// Auto-generated FusionAgent bootstrap for Neo4j.

// All managed nodes are labeled :FusionAgentManaged to avoid querying unrelated graph content.

// Safe to replay because every statement uses IF NOT EXISTS or MERGE.

CREATE CONSTRAINT workflow_pattern_pattern_id IF NOT EXISTS
FOR (wp:WorkflowPattern) REQUIRE wp.patternId IS UNIQUE;
CREATE CONSTRAINT algorithm_algo_id IF NOT EXISTS
FOR (algo:Algorithm) REQUIRE algo.algoId IS UNIQUE;
CREATE CONSTRAINT algorithm_parameter_spec_spec_id IF NOT EXISTS
FOR (ps:AlgorithmParameterSpec) REQUIRE ps.specId IS UNIQUE;
CREATE CONSTRAINT datasource_source_id IF NOT EXISTS
FOR (ds:DataSource) REQUIRE ds.sourceId IS UNIQUE;
CREATE CONSTRAINT output_schema_policy_policy_id IF NOT EXISTS
FOR (osp:OutputSchemaPolicy) REQUIRE osp.policyId IS UNIQUE;
CREATE CONSTRAINT datatype_type_id IF NOT EXISTS
FOR (dt:DataType) REQUIRE dt.typeId IS UNIQUE;
CREATE CONSTRAINT step_template_step_key IF NOT EXISTS
FOR (st:StepTemplate) REQUIRE st.stepKey IS UNIQUE;
CREATE CONSTRAINT workflow_instance_instance_id IF NOT EXISTS
FOR (run:WorkflowInstance) REQUIRE run.instanceId IS UNIQUE;
CREATE FULLTEXT INDEX wp_search IF NOT EXISTS
FOR (wp:WorkflowPattern) ON EACH [wp.patternId, wp.patternName];
CREATE FULLTEXT INDEX algo_search IF NOT EXISTS
FOR (algo:Algorithm) ON EACH [algo.algoId, algo.algoName];
CREATE FULLTEXT INDEX ds_search IF NOT EXISTS
FOR (ds:DataSource) ON EACH [ds.sourceId, ds.sourceName];

// Seed DataType nodes
MERGE (dt:DataType {typeId: "dt.raw.vector"}) SET dt:FusionAgentManaged SET dt += {theme: "generic", geometryType: "mixed", description: "Uploaded raw vector bundle.", graphNamespace: "fusionagent"};
MERGE (dt:DataType {typeId: "dt.building.bundle"}) SET dt:FusionAgentManaged SET dt += {theme: "building", geometryType: "polygon", description: "Prepared building fusion input bundle.", graphNamespace: "fusionagent"};
MERGE (dt:DataType {typeId: "dt.road.bundle"}) SET dt:FusionAgentManaged SET dt += {theme: "transportation", geometryType: "line", description: "Prepared road fusion input bundle.", graphNamespace: "fusionagent"};
MERGE (dt:DataType {typeId: "dt.building.fused"}) SET dt:FusionAgentManaged SET dt += {theme: "building", geometryType: "polygon", description: "Fused building output.", graphNamespace: "fusionagent"};
MERGE (dt:DataType {typeId: "dt.road.fused"}) SET dt:FusionAgentManaged SET dt += {theme: "transportation", geometryType: "line", description: "Fused road output.", graphNamespace: "fusionagent"};

// Seed Algorithm nodes and alternatives
MERGE (algo:Algorithm {algoId: "algo.fusion.building.v1"}) SET algo:FusionAgentManaged SET algo += {algoId: "algo.fusion.building.v1", algoName: "Building Fusion Legacy", inputTypes: ["dt.building.bundle"], outputType: "dt.building.fused", taskType: "building_fusion", toolRef: "adapters.building_adapter:run_building_fusion", successRate: 0.92, accuracyScore: 0.89, stabilityScore: 0.74, usageMode: "throughput", metadataJson: "{\"selection_profile\": \"primary\", \"evidence_basis\": \"legacy_default_runtime\"}", graphNamespace: "fusionagent"};
MERGE (algo:Algorithm {algoId: "algo.fusion.building.safe"}) SET algo:FusionAgentManaged SET algo += {algoId: "algo.fusion.building.safe", algoName: "Building Fusion Safe Fallback", inputTypes: ["dt.building.bundle"], outputType: "dt.building.fused", taskType: "building_fusion", toolRef: "adapters.building_adapter:run_building_fusion", successRate: 0.75, accuracyScore: 0.79, stabilityScore: 0.91, usageMode: "conservative", metadataJson: "{\"selection_profile\": \"fallback\", \"evidence_basis\": \"conservative_thresholds\"}", graphNamespace: "fusionagent"};
MERGE (algo:Algorithm {algoId: "algo.fusion.road.v1"}) SET algo:FusionAgentManaged SET algo += {algoId: "algo.fusion.road.v1", algoName: "Road Fusion Legacy", inputTypes: ["dt.road.bundle"], outputType: "dt.road.fused", taskType: "road_fusion", toolRef: "adapters.road_adapter:run_road_fusion", successRate: 0.9, accuracyScore: 0.86, stabilityScore: 0.72, usageMode: "throughput", metadataJson: "{\"selection_profile\": \"primary\", \"evidence_basis\": \"legacy_default_runtime\"}", graphNamespace: "fusionagent"};
MERGE (algo:Algorithm {algoId: "algo.fusion.road.safe"}) SET algo:FusionAgentManaged SET algo += {algoId: "algo.fusion.road.safe", algoName: "Road Fusion Safe Fallback", inputTypes: ["dt.road.bundle"], outputType: "dt.road.fused", taskType: "road_fusion", toolRef: "adapters.road_adapter:run_road_fusion", successRate: 0.72, accuracyScore: 0.77, stabilityScore: 0.9, usageMode: "conservative", metadataJson: "{\"selection_profile\": \"fallback\", \"evidence_basis\": \"conservative_thresholds\"}", graphNamespace: "fusionagent"};
MERGE (algo:Algorithm {algoId: "algo.transform.raw_to_building_bundle"}) SET algo:FusionAgentManaged SET algo += {algoId: "algo.transform.raw_to_building_bundle", algoName: "Raw Vector to Building Bundle", inputTypes: ["dt.raw.vector"], outputType: "dt.building.bundle", taskType: "transform", toolRef: "builtin:transform", successRate: 0.98, accuracyScore: 0.97, stabilityScore: 0.96, usageMode: "normalization", metadataJson: "{\"selection_profile\": \"preparation\", \"evidence_basis\": \"deterministic_transform\"}", graphNamespace: "fusionagent"};
MERGE (algo:Algorithm {algoId: "algo.transform.raw_to_road_bundle"}) SET algo:FusionAgentManaged SET algo += {algoId: "algo.transform.raw_to_road_bundle", algoName: "Raw Vector to Road Bundle", inputTypes: ["dt.raw.vector"], outputType: "dt.road.bundle", taskType: "transform", toolRef: "builtin:transform", successRate: 0.98, accuracyScore: 0.97, stabilityScore: 0.96, usageMode: "normalization", metadataJson: "{\"selection_profile\": \"preparation\", \"evidence_basis\": \"deterministic_transform\"}", graphNamespace: "fusionagent"};
MATCH (src:Algorithm:FusionAgentManaged {algoId: "algo.fusion.building.v1"}), (dst:Algorithm:FusionAgentManaged {algoId: "algo.fusion.building.safe"}) MERGE (src)-[:ALTERNATIVE_TO]->(dst);
MATCH (src:Algorithm:FusionAgentManaged {algoId: "algo.fusion.building.safe"}), (dst:Algorithm:FusionAgentManaged {algoId: "algo.fusion.building.v1"}) MERGE (src)-[:ALTERNATIVE_TO]->(dst);
MATCH (src:Algorithm:FusionAgentManaged {algoId: "algo.fusion.road.v1"}), (dst:Algorithm:FusionAgentManaged {algoId: "algo.fusion.road.safe"}) MERGE (src)-[:ALTERNATIVE_TO]->(dst);
MATCH (src:Algorithm:FusionAgentManaged {algoId: "algo.fusion.road.safe"}), (dst:Algorithm:FusionAgentManaged {algoId: "algo.fusion.road.v1"}) MERGE (src)-[:ALTERNATIVE_TO]->(dst);

// Seed AlgorithmParameterSpec nodes
MERGE (ps:AlgorithmParameterSpec {specId: "ps.algo.fusion.building.v1.match_similarity_threshold"}) SET ps:FusionAgentManaged SET ps += {specId: "ps.algo.fusion.building.v1.match_similarity_threshold", algoId: "algo.fusion.building.v1", key: "match_similarity_threshold", label: "Match Similarity Threshold", paramType: "float", default: 0.3, minValue: 0.0, maxValue: 1.0, unit: "ratio", description: "Pairs with similarity > this value are treated as matched (legacy label=1).", required: false, choices: null, tunable: true, optimizationTags: ["precision", "recall", "matching"], order: 10, graphNamespace: "fusionagent"};
MATCH (algo:Algorithm:FusionAgentManaged {algoId: "algo.fusion.building.v1"}), (ps:AlgorithmParameterSpec:FusionAgentManaged {specId: "ps.algo.fusion.building.v1.match_similarity_threshold"}) MERGE (algo)-[:HAS_PARAMETER_SPEC {order: 10}]->(ps);
MERGE (ps:AlgorithmParameterSpec {specId: "ps.algo.fusion.building.v1.one_to_one_min_area_similarity"}) SET ps:FusionAgentManaged SET ps += {specId: "ps.algo.fusion.building.v1.one_to_one_min_area_similarity", algoId: "algo.fusion.building.v1", key: "one_to_one_min_area_similarity", label: "One-to-One Min Area Similarity", paramType: "float", default: 0.3, minValue: 0.0, maxValue: 1.0, unit: "ratio", description: "For 1:1 matches, sim_area must be >= this value to fuse as one-to-one.", required: false, choices: null, tunable: true, optimizationTags: ["precision", "stability", "shape_consistency"], order: 20, graphNamespace: "fusionagent"};
MATCH (algo:Algorithm:FusionAgentManaged {algoId: "algo.fusion.building.v1"}), (ps:AlgorithmParameterSpec:FusionAgentManaged {specId: "ps.algo.fusion.building.v1.one_to_one_min_area_similarity"}) MERGE (algo)-[:HAS_PARAMETER_SPEC {order: 20}]->(ps);
MERGE (ps:AlgorithmParameterSpec {specId: "ps.algo.fusion.building.v1.one_to_one_min_shape_similarity"}) SET ps:FusionAgentManaged SET ps += {specId: "ps.algo.fusion.building.v1.one_to_one_min_shape_similarity", algoId: "algo.fusion.building.v1", key: "one_to_one_min_shape_similarity", label: "One-to-One Min Shape Similarity", paramType: "float", default: 0.3, minValue: 0.0, maxValue: 1.0, unit: "ratio", description: "For 1:1 matches, sim_shape must be >= this value to fuse as one-to-one.", required: false, choices: null, tunable: true, optimizationTags: ["precision", "stability", "shape_consistency"], order: 30, graphNamespace: "fusionagent"};
MATCH (algo:Algorithm:FusionAgentManaged {algoId: "algo.fusion.building.v1"}), (ps:AlgorithmParameterSpec:FusionAgentManaged {specId: "ps.algo.fusion.building.v1.one_to_one_min_shape_similarity"}) MERGE (algo)-[:HAS_PARAMETER_SPEC {order: 30}]->(ps);
MERGE (ps:AlgorithmParameterSpec {specId: "ps.algo.fusion.building.v1.one_to_one_min_overlap_similarity"}) SET ps:FusionAgentManaged SET ps += {specId: "ps.algo.fusion.building.v1.one_to_one_min_overlap_similarity", algoId: "algo.fusion.building.v1", key: "one_to_one_min_overlap_similarity", label: "One-to-One Min Overlap Similarity", paramType: "float", default: 0.3, minValue: 0.0, maxValue: 1.0, unit: "ratio", description: "For 1:1 matches, sim_overlap must be >= this value to fuse as one-to-one.", required: false, choices: null, tunable: true, optimizationTags: ["precision", "recall", "overlap_consistency"], order: 40, graphNamespace: "fusionagent"};
MATCH (algo:Algorithm:FusionAgentManaged {algoId: "algo.fusion.building.v1"}), (ps:AlgorithmParameterSpec:FusionAgentManaged {specId: "ps.algo.fusion.building.v1.one_to_one_min_overlap_similarity"}) MERGE (algo)-[:HAS_PARAMETER_SPEC {order: 40}]->(ps);
MERGE (ps:AlgorithmParameterSpec {specId: "ps.algo.fusion.building.safe.match_similarity_threshold"}) SET ps:FusionAgentManaged SET ps += {specId: "ps.algo.fusion.building.safe.match_similarity_threshold", algoId: "algo.fusion.building.safe", key: "match_similarity_threshold", label: "Match Similarity Threshold", paramType: "float", default: 0.4, minValue: 0.0, maxValue: 1.0, unit: "ratio", description: "Conservative match threshold for safe mode.", required: false, choices: null, tunable: true, optimizationTags: ["precision", "stability", "matching"], order: 10, graphNamespace: "fusionagent"};
MATCH (algo:Algorithm:FusionAgentManaged {algoId: "algo.fusion.building.safe"}), (ps:AlgorithmParameterSpec:FusionAgentManaged {specId: "ps.algo.fusion.building.safe.match_similarity_threshold"}) MERGE (algo)-[:HAS_PARAMETER_SPEC {order: 10}]->(ps);
MERGE (ps:AlgorithmParameterSpec {specId: "ps.algo.fusion.building.safe.one_to_one_min_area_similarity"}) SET ps:FusionAgentManaged SET ps += {specId: "ps.algo.fusion.building.safe.one_to_one_min_area_similarity", algoId: "algo.fusion.building.safe", key: "one_to_one_min_area_similarity", label: "One-to-One Min Area Similarity", paramType: "float", default: 0.45, minValue: 0.0, maxValue: 1.0, unit: "ratio", description: "Conservative area similarity threshold for safe mode.", required: false, choices: null, tunable: true, optimizationTags: ["precision", "stability", "shape_consistency"], order: 20, graphNamespace: "fusionagent"};
MATCH (algo:Algorithm:FusionAgentManaged {algoId: "algo.fusion.building.safe"}), (ps:AlgorithmParameterSpec:FusionAgentManaged {specId: "ps.algo.fusion.building.safe.one_to_one_min_area_similarity"}) MERGE (algo)-[:HAS_PARAMETER_SPEC {order: 20}]->(ps);
MERGE (ps:AlgorithmParameterSpec {specId: "ps.algo.fusion.building.safe.one_to_one_min_shape_similarity"}) SET ps:FusionAgentManaged SET ps += {specId: "ps.algo.fusion.building.safe.one_to_one_min_shape_similarity", algoId: "algo.fusion.building.safe", key: "one_to_one_min_shape_similarity", label: "One-to-One Min Shape Similarity", paramType: "float", default: 0.45, minValue: 0.0, maxValue: 1.0, unit: "ratio", description: "Conservative shape similarity threshold for safe mode.", required: false, choices: null, tunable: true, optimizationTags: ["precision", "stability", "shape_consistency"], order: 30, graphNamespace: "fusionagent"};
MATCH (algo:Algorithm:FusionAgentManaged {algoId: "algo.fusion.building.safe"}), (ps:AlgorithmParameterSpec:FusionAgentManaged {specId: "ps.algo.fusion.building.safe.one_to_one_min_shape_similarity"}) MERGE (algo)-[:HAS_PARAMETER_SPEC {order: 30}]->(ps);
MERGE (ps:AlgorithmParameterSpec {specId: "ps.algo.fusion.building.safe.one_to_one_min_overlap_similarity"}) SET ps:FusionAgentManaged SET ps += {specId: "ps.algo.fusion.building.safe.one_to_one_min_overlap_similarity", algoId: "algo.fusion.building.safe", key: "one_to_one_min_overlap_similarity", label: "One-to-One Min Overlap Similarity", paramType: "float", default: 0.4, minValue: 0.0, maxValue: 1.0, unit: "ratio", description: "Conservative one-to-one overlap threshold for safe mode.", required: false, choices: null, tunable: true, optimizationTags: ["precision", "stability", "overlap_consistency"], order: 40, graphNamespace: "fusionagent"};
MATCH (algo:Algorithm:FusionAgentManaged {algoId: "algo.fusion.building.safe"}), (ps:AlgorithmParameterSpec:FusionAgentManaged {specId: "ps.algo.fusion.building.safe.one_to_one_min_overlap_similarity"}) MERGE (algo)-[:HAS_PARAMETER_SPEC {order: 40}]->(ps);
MERGE (ps:AlgorithmParameterSpec {specId: "ps.algo.fusion.road.v1.angle_threshold_deg"}) SET ps:FusionAgentManaged SET ps += {specId: "ps.algo.fusion.road.v1.angle_threshold_deg", algoId: "algo.fusion.road.v1", key: "angle_threshold_deg", label: "Split Angle Threshold", paramType: "int", default: 135, minValue: 0.0, maxValue: 180.0, unit: "deg", description: "Split lines at sharp turns: angles below this threshold trigger a split.", required: false, choices: null, tunable: true, optimizationTags: ["stability", "segmentation"], order: 10, graphNamespace: "fusionagent"};
MATCH (algo:Algorithm:FusionAgentManaged {algoId: "algo.fusion.road.v1"}), (ps:AlgorithmParameterSpec:FusionAgentManaged {specId: "ps.algo.fusion.road.v1.angle_threshold_deg"}) MERGE (algo)-[:HAS_PARAMETER_SPEC {order: 10}]->(ps);
MERGE (ps:AlgorithmParameterSpec {specId: "ps.algo.fusion.road.v1.snap_tolerance_m"}) SET ps:FusionAgentManaged SET ps += {specId: "ps.algo.fusion.road.v1.snap_tolerance_m", algoId: "algo.fusion.road.v1", key: "snap_tolerance_m", label: "Snap Tolerance", paramType: "float", default: 1.0, minValue: 0.0, maxValue: 10.0, unit: "m", description: "Endpoint snap tolerance used when normalizing line endpoints.", required: false, choices: null, tunable: true, optimizationTags: ["stability", "topology"], order: 20, graphNamespace: "fusionagent"};
MATCH (algo:Algorithm:FusionAgentManaged {algoId: "algo.fusion.road.v1"}), (ps:AlgorithmParameterSpec:FusionAgentManaged {specId: "ps.algo.fusion.road.v1.snap_tolerance_m"}) MERGE (algo)-[:HAS_PARAMETER_SPEC {order: 20}]->(ps);
MERGE (ps:AlgorithmParameterSpec {specId: "ps.algo.fusion.road.v1.match_buffer_m"}) SET ps:FusionAgentManaged SET ps += {specId: "ps.algo.fusion.road.v1.match_buffer_m", algoId: "algo.fusion.road.v1", key: "match_buffer_m", label: "Match Buffer Distance", paramType: "float", default: 20.0, minValue: 0.0, maxValue: 100.0, unit: "m", description: "Buffer radius for candidate matching between OSM and reference lines.", required: false, choices: null, tunable: true, optimizationTags: ["recall", "matching"], order: 30, graphNamespace: "fusionagent"};
MATCH (algo:Algorithm:FusionAgentManaged {algoId: "algo.fusion.road.v1"}), (ps:AlgorithmParameterSpec:FusionAgentManaged {specId: "ps.algo.fusion.road.v1.match_buffer_m"}) MERGE (algo)-[:HAS_PARAMETER_SPEC {order: 30}]->(ps);
MERGE (ps:AlgorithmParameterSpec {specId: "ps.algo.fusion.road.v1.max_hausdorff_m"}) SET ps:FusionAgentManaged SET ps += {specId: "ps.algo.fusion.road.v1.max_hausdorff_m", algoId: "algo.fusion.road.v1", key: "max_hausdorff_m", label: "Max Hausdorff Distance", paramType: "float", default: 15.0, minValue: 0.0, maxValue: 100.0, unit: "m", description: "Maximum Hausdorff distance allowed to consider two lines as a match.", required: false, choices: null, tunable: true, optimizationTags: ["precision", "stability", "matching"], order: 40, graphNamespace: "fusionagent"};
MATCH (algo:Algorithm:FusionAgentManaged {algoId: "algo.fusion.road.v1"}), (ps:AlgorithmParameterSpec:FusionAgentManaged {specId: "ps.algo.fusion.road.v1.max_hausdorff_m"}) MERGE (algo)-[:HAS_PARAMETER_SPEC {order: 40}]->(ps);
MERGE (ps:AlgorithmParameterSpec {specId: "ps.algo.fusion.road.v1.dedupe_buffer_m"}) SET ps:FusionAgentManaged SET ps += {specId: "ps.algo.fusion.road.v1.dedupe_buffer_m", algoId: "algo.fusion.road.v1", key: "dedupe_buffer_m", label: "Dedupe Buffer Distance", paramType: "float", default: 15.0, minValue: 0.0, maxValue: 100.0, unit: "m", description: "Buffer distance used during post-fusion deduplication.", required: false, choices: null, tunable: true, optimizationTags: ["stability", "deduplication"], order: 50, graphNamespace: "fusionagent"};
MATCH (algo:Algorithm:FusionAgentManaged {algoId: "algo.fusion.road.v1"}), (ps:AlgorithmParameterSpec:FusionAgentManaged {specId: "ps.algo.fusion.road.v1.dedupe_buffer_m"}) MERGE (algo)-[:HAS_PARAMETER_SPEC {order: 50}]->(ps);
MERGE (ps:AlgorithmParameterSpec {specId: "ps.algo.fusion.road.safe.angle_threshold_deg"}) SET ps:FusionAgentManaged SET ps += {specId: "ps.algo.fusion.road.safe.angle_threshold_deg", algoId: "algo.fusion.road.safe", key: "angle_threshold_deg", label: "Split Angle Threshold", paramType: "int", default: 120, minValue: 0.0, maxValue: 180.0, unit: "deg", description: "Conservative split angle threshold for safe mode.", required: false, choices: null, tunable: true, optimizationTags: ["stability", "segmentation"], order: 10, graphNamespace: "fusionagent"};
MATCH (algo:Algorithm:FusionAgentManaged {algoId: "algo.fusion.road.safe"}), (ps:AlgorithmParameterSpec:FusionAgentManaged {specId: "ps.algo.fusion.road.safe.angle_threshold_deg"}) MERGE (algo)-[:HAS_PARAMETER_SPEC {order: 10}]->(ps);
MERGE (ps:AlgorithmParameterSpec {specId: "ps.algo.fusion.road.safe.snap_tolerance_m"}) SET ps:FusionAgentManaged SET ps += {specId: "ps.algo.fusion.road.safe.snap_tolerance_m", algoId: "algo.fusion.road.safe", key: "snap_tolerance_m", label: "Snap Tolerance", paramType: "float", default: 0.75, minValue: 0.0, maxValue: 10.0, unit: "m", description: "Conservative endpoint snap tolerance for safe mode.", required: false, choices: null, tunable: true, optimizationTags: ["stability", "topology"], order: 20, graphNamespace: "fusionagent"};
MATCH (algo:Algorithm:FusionAgentManaged {algoId: "algo.fusion.road.safe"}), (ps:AlgorithmParameterSpec:FusionAgentManaged {specId: "ps.algo.fusion.road.safe.snap_tolerance_m"}) MERGE (algo)-[:HAS_PARAMETER_SPEC {order: 20}]->(ps);
MERGE (ps:AlgorithmParameterSpec {specId: "ps.algo.fusion.road.safe.match_buffer_m"}) SET ps:FusionAgentManaged SET ps += {specId: "ps.algo.fusion.road.safe.match_buffer_m", algoId: "algo.fusion.road.safe", key: "match_buffer_m", label: "Match Buffer Distance", paramType: "float", default: 15.0, minValue: 0.0, maxValue: 100.0, unit: "m", description: "Conservative match buffer for safe mode.", required: false, choices: null, tunable: true, optimizationTags: ["precision", "matching"], order: 30, graphNamespace: "fusionagent"};
MATCH (algo:Algorithm:FusionAgentManaged {algoId: "algo.fusion.road.safe"}), (ps:AlgorithmParameterSpec:FusionAgentManaged {specId: "ps.algo.fusion.road.safe.match_buffer_m"}) MERGE (algo)-[:HAS_PARAMETER_SPEC {order: 30}]->(ps);
MERGE (ps:AlgorithmParameterSpec {specId: "ps.algo.fusion.road.safe.max_hausdorff_m"}) SET ps:FusionAgentManaged SET ps += {specId: "ps.algo.fusion.road.safe.max_hausdorff_m", algoId: "algo.fusion.road.safe", key: "max_hausdorff_m", label: "Max Hausdorff Distance", paramType: "float", default: 10.0, minValue: 0.0, maxValue: 100.0, unit: "m", description: "Conservative Hausdorff threshold for safe mode.", required: false, choices: null, tunable: true, optimizationTags: ["precision", "stability", "matching"], order: 40, graphNamespace: "fusionagent"};
MATCH (algo:Algorithm:FusionAgentManaged {algoId: "algo.fusion.road.safe"}), (ps:AlgorithmParameterSpec:FusionAgentManaged {specId: "ps.algo.fusion.road.safe.max_hausdorff_m"}) MERGE (algo)-[:HAS_PARAMETER_SPEC {order: 40}]->(ps);
MERGE (ps:AlgorithmParameterSpec {specId: "ps.algo.fusion.road.safe.dedupe_buffer_m"}) SET ps:FusionAgentManaged SET ps += {specId: "ps.algo.fusion.road.safe.dedupe_buffer_m", algoId: "algo.fusion.road.safe", key: "dedupe_buffer_m", label: "Dedupe Buffer Distance", paramType: "float", default: 12.0, minValue: 0.0, maxValue: 100.0, unit: "m", description: "Conservative dedupe buffer for safe mode.", required: false, choices: null, tunable: true, optimizationTags: ["stability", "deduplication"], order: 50, graphNamespace: "fusionagent"};
MATCH (algo:Algorithm:FusionAgentManaged {algoId: "algo.fusion.road.safe"}), (ps:AlgorithmParameterSpec:FusionAgentManaged {specId: "ps.algo.fusion.road.safe.dedupe_buffer_m"}) MERGE (algo)-[:HAS_PARAMETER_SPEC {order: 50}]->(ps);

// Seed DataSource nodes
MERGE (ds:DataSource {sourceId: "upload.bundle"}) SET ds:FusionAgentManaged SET ds += {sourceId: "upload.bundle", sourceName: "Uploaded Bundle", supportedTypes: ["dt.building.bundle", "dt.road.bundle", "dt.raw.vector"], disasterTypes: ["generic", "flood", "earthquake", "typhoon"], qualityScore: 1.0, sourceKind: "local_upload", qualityTier: "operator_provided", freshnessCategory: "request_bound", freshnessHours: 0, freshnessScore: 1.0, supportedJobTypes: ["building", "road"], supportedGeometryTypes: ["mixed", "polygon", "line"], metadataJson: "{\"kind\": \"local\"}", graphNamespace: "fusionagent"};
MERGE (ds:DataSource {sourceId: "catalog.flood.building"}) SET ds:FusionAgentManaged SET ds += {sourceId: "catalog.flood.building", sourceName: "Flood Building Catalog", supportedTypes: ["dt.building.bundle"], disasterTypes: ["flood", "generic"], qualityScore: 0.86, sourceKind: "catalog", qualityTier: "curated", freshnessCategory: "event_snapshot", freshnessHours: 72, freshnessScore: 0.74, supportedJobTypes: ["building"], supportedGeometryTypes: ["polygon"], metadataJson: "{\"kind\": \"catalog\", \"priority\": 2}", graphNamespace: "fusionagent"};
MERGE (ds:DataSource {sourceId: "catalog.earthquake.building"}) SET ds:FusionAgentManaged SET ds += {sourceId: "catalog.earthquake.building", sourceName: "Earthquake Building Catalog", supportedTypes: ["dt.building.bundle"], disasterTypes: ["earthquake", "generic"], qualityScore: 0.88, sourceKind: "catalog", qualityTier: "curated", freshnessCategory: "event_snapshot", freshnessHours: 96, freshnessScore: 0.71, supportedJobTypes: ["building"], supportedGeometryTypes: ["polygon"], metadataJson: "{\"kind\": \"catalog\", \"priority\": 2}", graphNamespace: "fusionagent"};
MERGE (ds:DataSource {sourceId: "catalog.earthquake.road"}) SET ds:FusionAgentManaged SET ds += {sourceId: "catalog.earthquake.road", sourceName: "Earthquake Road Catalog", supportedTypes: ["dt.road.bundle"], disasterTypes: ["earthquake", "generic"], qualityScore: 0.84, sourceKind: "catalog", qualityTier: "curated", freshnessCategory: "event_snapshot", freshnessHours: 96, freshnessScore: 0.69, supportedJobTypes: ["road"], supportedGeometryTypes: ["line"], metadataJson: "{\"kind\": \"catalog\", \"priority\": 2}", graphNamespace: "fusionagent"};
MERGE (ds:DataSource {sourceId: "catalog.typhoon.road"}) SET ds:FusionAgentManaged SET ds += {sourceId: "catalog.typhoon.road", sourceName: "Typhoon Road Catalog", supportedTypes: ["dt.road.bundle"], disasterTypes: ["typhoon", "generic"], qualityScore: 0.87, sourceKind: "catalog", qualityTier: "curated", freshnessCategory: "event_snapshot", freshnessHours: 48, freshnessScore: 0.78, supportedJobTypes: ["road"], supportedGeometryTypes: ["line"], metadataJson: "{\"kind\": \"catalog\", \"priority\": 2}", graphNamespace: "fusionagent"};

// Seed OutputSchemaPolicy nodes
MERGE (osp:OutputSchemaPolicy {policyId: "osp.building.fused.v1"}) SET osp:FusionAgentManaged SET osp += {policyId: "osp.building.fused.v1", outputType: "dt.building.fused", jobType: "building", retentionMode: "preserve_listed", requiredFields: ["geometry"], optionalFields: ["osm_id", "fclass", "name", "type", "longitude", "latitude", "area_in_me", "confidence"], renameHintsJson: "{\"geometry_x\": \"geometry\", \"geometry_y\": \"geometry\"}", compatibilityBasis: "field_names", metadataJson: "{\"policy_scope\": \"current_runtime\", \"notes\": \"Expose stable fused building columns without changing adapter behavior.\"}", graphNamespace: "fusionagent"};
MATCH (osp:OutputSchemaPolicy:FusionAgentManaged {policyId: "osp.building.fused.v1"}), (dt:DataType:FusionAgentManaged {typeId: "dt.building.fused"}) MERGE (osp)-[:APPLIES_TO_OUTPUT_TYPE]->(dt);
MERGE (osp:OutputSchemaPolicy {policyId: "osp.road.fused.v1"}) SET osp:FusionAgentManaged SET osp += {policyId: "osp.road.fused.v1", outputType: "dt.road.fused", jobType: "road", retentionMode: "preserve_listed", requiredFields: ["geometry"], optionalFields: ["osm_id", "FID_1", "fclass"], renameHintsJson: "{}", compatibilityBasis: "field_names", metadataJson: "{\"policy_scope\": \"current_runtime\", \"notes\": \"Road output schema remains metadata-only until explicit output policy execution is added.\"}", graphNamespace: "fusionagent"};
MATCH (osp:OutputSchemaPolicy:FusionAgentManaged {policyId: "osp.road.fused.v1"}), (dt:DataType:FusionAgentManaged {typeId: "dt.road.fused"}) MERGE (osp)-[:APPLIES_TO_OUTPUT_TYPE]->(dt);

// Seed WorkflowPattern and StepTemplate nodes
MERGE (wp:WorkflowPattern {patternId: "wp.flood.building.default"}) SET wp:FusionAgentManaged SET wp += {patternId: "wp.flood.building.default", patternName: "Flood Building Fusion", jobType: "building", disasterTypes: ["flood", "typhoon", "generic"], successRate: 0.88, metadataJson: "{\"version\": \"1.0.0\", \"runtime_status\": \"runtime_candidate\", \"scenario_focus\": \"flood\", \"strategy\": \"throughput\"}", graphNamespace: "fusionagent"};
MERGE (st:StepTemplate {stepKey: "wp.flood.building.default#1"}) SET st:FusionAgentManaged SET st += {stepKey: "wp.flood.building.default#1", order: 1, name: "building_fusion", algorithmId: "algo.fusion.building.v1", inputDataType: "dt.building.bundle", outputDataType: "dt.building.fused", dataSourceId: "upload.bundle", dependsOn: [], isOptional: false, graphNamespace: "fusionagent"};
MATCH (wp:WorkflowPattern:FusionAgentManaged {patternId: "wp.flood.building.default"}), (st:StepTemplate:FusionAgentManaged {stepKey: "wp.flood.building.default#1"}) MERGE (wp)-[:HAS_STEP {order: 1}]->(st);
MERGE (wp:WorkflowPattern {patternId: "wp.flood.building.safe"}) SET wp:FusionAgentManaged SET wp += {patternId: "wp.flood.building.safe", patternName: "Flood Building Fusion Safe Route", jobType: "building", disasterTypes: ["flood", "generic"], successRate: 0.82, metadataJson: "{\"version\": \"1.0.0\", \"runtime_status\": \"runtime_candidate\", \"scenario_focus\": \"flood\", \"mode\": \"safe\", \"strategy\": \"conservative\"}", graphNamespace: "fusionagent"};
MERGE (st:StepTemplate {stepKey: "wp.flood.building.safe#1"}) SET st:FusionAgentManaged SET st += {stepKey: "wp.flood.building.safe#1", order: 1, name: "building_fusion_safe", algorithmId: "algo.fusion.building.safe", inputDataType: "dt.building.bundle", outputDataType: "dt.building.fused", dataSourceId: "upload.bundle", dependsOn: [], isOptional: false, graphNamespace: "fusionagent"};
MATCH (wp:WorkflowPattern:FusionAgentManaged {patternId: "wp.flood.building.safe"}), (st:StepTemplate:FusionAgentManaged {stepKey: "wp.flood.building.safe#1"}) MERGE (wp)-[:HAS_STEP {order: 1}]->(st);
MERGE (wp:WorkflowPattern {patternId: "wp.earthquake.building.default"}) SET wp:FusionAgentManaged SET wp += {patternId: "wp.earthquake.building.default", patternName: "Earthquake Building Fusion", jobType: "building", disasterTypes: ["earthquake"], successRate: 0.91, metadataJson: "{\"version\": \"1.0.0\", \"runtime_status\": \"runtime_candidate\", \"scenario_focus\": \"earthquake\", \"strategy\": \"throughput\"}", graphNamespace: "fusionagent"};
MERGE (st:StepTemplate {stepKey: "wp.earthquake.building.default#1"}) SET st:FusionAgentManaged SET st += {stepKey: "wp.earthquake.building.default#1", order: 1, name: "building_fusion_earthquake", algorithmId: "algo.fusion.building.v1", inputDataType: "dt.building.bundle", outputDataType: "dt.building.fused", dataSourceId: "upload.bundle", dependsOn: [], isOptional: false, graphNamespace: "fusionagent"};
MATCH (wp:WorkflowPattern:FusionAgentManaged {patternId: "wp.earthquake.building.default"}), (st:StepTemplate:FusionAgentManaged {stepKey: "wp.earthquake.building.default#1"}) MERGE (wp)-[:HAS_STEP {order: 1}]->(st);
MERGE (wp:WorkflowPattern {patternId: "wp.earthquake.building.safe"}) SET wp:FusionAgentManaged SET wp += {patternId: "wp.earthquake.building.safe", patternName: "Earthquake Building Fusion Safe Route", jobType: "building", disasterTypes: ["earthquake"], successRate: 0.85, metadataJson: "{\"version\": \"1.0.0\", \"runtime_status\": \"runtime_candidate\", \"scenario_focus\": \"earthquake\", \"mode\": \"safe\", \"strategy\": \"conservative\"}", graphNamespace: "fusionagent"};
MERGE (st:StepTemplate {stepKey: "wp.earthquake.building.safe#1"}) SET st:FusionAgentManaged SET st += {stepKey: "wp.earthquake.building.safe#1", order: 1, name: "building_fusion_safe", algorithmId: "algo.fusion.building.safe", inputDataType: "dt.building.bundle", outputDataType: "dt.building.fused", dataSourceId: "upload.bundle", dependsOn: [], isOptional: false, graphNamespace: "fusionagent"};
MATCH (wp:WorkflowPattern:FusionAgentManaged {patternId: "wp.earthquake.building.safe"}), (st:StepTemplate:FusionAgentManaged {stepKey: "wp.earthquake.building.safe#1"}) MERGE (wp)-[:HAS_STEP {order: 1}]->(st);
MERGE (wp:WorkflowPattern {patternId: "wp.flood.road.default"}) SET wp:FusionAgentManaged SET wp += {patternId: "wp.flood.road.default", patternName: "Flood Road Fusion", jobType: "road", disasterTypes: ["flood", "earthquake", "generic"], successRate: 0.86, metadataJson: "{\"version\": \"1.0.0\", \"runtime_status\": \"runtime_candidate\", \"scenario_focus\": \"flood\", \"strategy\": \"throughput\"}", graphNamespace: "fusionagent"};
MERGE (st:StepTemplate {stepKey: "wp.flood.road.default#1"}) SET st:FusionAgentManaged SET st += {stepKey: "wp.flood.road.default#1", order: 1, name: "road_fusion", algorithmId: "algo.fusion.road.v1", inputDataType: "dt.road.bundle", outputDataType: "dt.road.fused", dataSourceId: "upload.bundle", dependsOn: [], isOptional: false, graphNamespace: "fusionagent"};
MATCH (wp:WorkflowPattern:FusionAgentManaged {patternId: "wp.flood.road.default"}), (st:StepTemplate:FusionAgentManaged {stepKey: "wp.flood.road.default#1"}) MERGE (wp)-[:HAS_STEP {order: 1}]->(st);
MERGE (wp:WorkflowPattern {patternId: "wp.flood.road.safe"}) SET wp:FusionAgentManaged SET wp += {patternId: "wp.flood.road.safe", patternName: "Flood Road Fusion Safe Route", jobType: "road", disasterTypes: ["flood", "generic"], successRate: 0.81, metadataJson: "{\"version\": \"1.0.0\", \"runtime_status\": \"runtime_candidate\", \"scenario_focus\": \"flood\", \"mode\": \"safe\", \"strategy\": \"conservative\"}", graphNamespace: "fusionagent"};
MERGE (st:StepTemplate {stepKey: "wp.flood.road.safe#1"}) SET st:FusionAgentManaged SET st += {stepKey: "wp.flood.road.safe#1", order: 1, name: "road_fusion_safe", algorithmId: "algo.fusion.road.safe", inputDataType: "dt.road.bundle", outputDataType: "dt.road.fused", dataSourceId: "upload.bundle", dependsOn: [], isOptional: false, graphNamespace: "fusionagent"};
MATCH (wp:WorkflowPattern:FusionAgentManaged {patternId: "wp.flood.road.safe"}), (st:StepTemplate:FusionAgentManaged {stepKey: "wp.flood.road.safe#1"}) MERGE (wp)-[:HAS_STEP {order: 1}]->(st);
MERGE (wp:WorkflowPattern {patternId: "wp.typhoon.road.default"}) SET wp:FusionAgentManaged SET wp += {patternId: "wp.typhoon.road.default", patternName: "Typhoon Road Fusion", jobType: "road", disasterTypes: ["typhoon"], successRate: 0.9, metadataJson: "{\"version\": \"1.0.0\", \"runtime_status\": \"runtime_candidate\", \"scenario_focus\": \"typhoon\", \"strategy\": \"throughput\"}", graphNamespace: "fusionagent"};
MERGE (st:StepTemplate {stepKey: "wp.typhoon.road.default#1"}) SET st:FusionAgentManaged SET st += {stepKey: "wp.typhoon.road.default#1", order: 1, name: "road_fusion_typhoon", algorithmId: "algo.fusion.road.v1", inputDataType: "dt.road.bundle", outputDataType: "dt.road.fused", dataSourceId: "upload.bundle", dependsOn: [], isOptional: false, graphNamespace: "fusionagent"};
MATCH (wp:WorkflowPattern:FusionAgentManaged {patternId: "wp.typhoon.road.default"}), (st:StepTemplate:FusionAgentManaged {stepKey: "wp.typhoon.road.default#1"}) MERGE (wp)-[:HAS_STEP {order: 1}]->(st);
MERGE (wp:WorkflowPattern {patternId: "wp.typhoon.road.safe"}) SET wp:FusionAgentManaged SET wp += {patternId: "wp.typhoon.road.safe", patternName: "Typhoon Road Fusion Safe Route", jobType: "road", disasterTypes: ["typhoon"], successRate: 0.84, metadataJson: "{\"version\": \"1.0.0\", \"runtime_status\": \"runtime_candidate\", \"scenario_focus\": \"typhoon\", \"mode\": \"safe\", \"strategy\": \"conservative\"}", graphNamespace: "fusionagent"};
MERGE (st:StepTemplate {stepKey: "wp.typhoon.road.safe#1"}) SET st:FusionAgentManaged SET st += {stepKey: "wp.typhoon.road.safe#1", order: 1, name: "road_fusion_safe", algorithmId: "algo.fusion.road.safe", inputDataType: "dt.road.bundle", outputDataType: "dt.road.fused", dataSourceId: "upload.bundle", dependsOn: [], isOptional: false, graphNamespace: "fusionagent"};
MATCH (wp:WorkflowPattern:FusionAgentManaged {patternId: "wp.typhoon.road.safe"}), (st:StepTemplate:FusionAgentManaged {stepKey: "wp.typhoon.road.safe#1"}) MERGE (wp)-[:HAS_STEP {order: 1}]->(st);

// Seed transform graph
MATCH (src:DataType:FusionAgentManaged {typeId: "dt.raw.vector"}), (dst:DataType:FusionAgentManaged {typeId: "dt.building.bundle"}) MERGE (src)-[:CAN_TRANSFORM_TO]->(dst);
MATCH (src:DataType:FusionAgentManaged {typeId: "dt.raw.vector"}), (dst:DataType:FusionAgentManaged {typeId: "dt.road.bundle"}) MERGE (src)-[:CAN_TRANSFORM_TO]->(dst);