from __future__ import annotations

from typing import Any, Dict, List

from llm.providers.base import LLMProvider


class MockLLMProvider(LLMProvider):
    def generate_workflow_plan(self, system_prompt: str, context: Dict[str, Any]) -> Dict[str, Any]:
        candidates: List[Dict[str, Any]] = context.get("candidate_patterns", [])
        trigger: Dict[str, Any] = context.get("trigger", {})
        job_type: str = context.get("job_type", "building")
        if not candidates:
            raise ValueError("No candidate patterns available for planning.")

        best = candidates[0]
        tasks = []
        for idx, step in enumerate(best.get("steps", []), start=1):
            tasks.append(
                {
                    "step": idx,
                    "name": step.get("name", f"step_{idx}"),
                    "description": f"Execute {step.get('algorithm_id', 'algorithm')}",
                    "algorithm_id": step.get("algorithm_id", ""),
                    "input": {
                        "data_type_id": step.get("input_data_type", "dt.raw.vector"),
                        "data_source_id": step.get("data_source_id", "upload.bundle"),
                        "parameters": {},
                    },
                    "output": {
                        "data_type_id": step.get("output_data_type", "dt.raw.vector"),
                        "description": "Auto generated by mock LLM provider.",
                    },
                    "depends_on": step.get("depends_on", []),
                    "is_transform": False,
                    "kg_validated": False,
                    "alternatives": [],
                }
            )

        return {
            "workflow_id": f"wf_{job_type}_{best.get('pattern_id', 'default')}",
            "trigger": trigger,
            "context": {
                "job_type": job_type,
                "disaster_type": trigger.get("disaster_type"),
                "source": "mock_llm",
            },
            "tasks": tasks,
            "expected_output": f"{job_type} fused shapefile",
            "estimated_time": "5m",
        }

