from __future__ import annotations

from kg.models import AlgorithmNode, AlgorithmParameterSpec, DataTypeNode, PatternStep, WorkflowPatternNode
from schemas.fusion import JobType


def _param(
    algo_id: str,
    key: str,
    *,
    default,
    param_type: str = "float",
    min_value: float | None = None,
    max_value: float | None = None,
    unit: str | None = None,
    order: int = 0,
    tags: list[str] | None = None,
) -> AlgorithmParameterSpec:
    return AlgorithmParameterSpec(
        spec_id=f"ps.{algo_id}.{key}",
        algo_id=algo_id,
        key=key,
        label=key.replace("_", " ").title(),
        param_type=param_type,
        default=default,
        min_value=min_value,
        max_value=max_value,
        unit=unit,
        description=f"FusionCode parameter `{key}` for {algo_id}.",
        required=False,
        tunable=True,
        optimization_tags=tags or [],
        order=order,
    )


FUSIONCODE_DATA_TYPES = {
    "dt.building.normalized_set": DataTypeNode(
        type_id="dt.building.normalized_set",
        theme="building",
        geometry_type="polygon",
        description="Normalized named building sources after CRS, geometry and source-label preparation.",
    ),
    "dt.building.presence_validated_set": DataTypeNode(
        type_id="dt.building.presence_validated_set",
        theme="building",
        geometry_type="polygon",
        description="Building sources enriched with presence-raster support and existence status.",
    ),
    "dt.building.match_candidate_graph": DataTypeNode(
        type_id="dt.building.match_candidate_graph",
        theme="building",
        geometry_type="graph",
        description="FusionCode V8 candidate edge graph for a pair of building sources.",
    ),
    "dt.building.match_components": DataTypeNode(
        type_id="dt.building.match_components",
        theme="building",
        geometry_type="graph",
        description="Accepted V8 building match components and relationship groups.",
    ),
    "dt.building.fused_raw": DataTypeNode(
        type_id="dt.building.fused_raw",
        theme="building",
        geometry_type="polygon",
        description="Raw cascaded building fusion rows before conflict optimization.",
    ),
    "dt.building.road_topology_adjusted": DataTypeNode(
        type_id="dt.building.road_topology_adjusted",
        theme="building",
        geometry_type="polygon",
        description="Fused buildings after road-aware topology adjustment.",
    ),
    "dt.building.conflict_optimized": DataTypeNode(
        type_id="dt.building.conflict_optimized",
        theme="building",
        geometry_type="polygon",
        description="Fused buildings after spatial conflict graph optimization.",
    ),
    "dt.building.height_enriched": DataTypeNode(
        type_id="dt.building.height_enriched",
        theme="building",
        geometry_type="polygon",
        description="Fused buildings enriched with height raster values.",
    ),
    "dt.building.quality_report": DataTypeNode(
        type_id="dt.building.quality_report",
        theme="building",
        geometry_type="none",
        description="Quality and conflict metrics for the building fusion run.",
    ),
    "dt.raster.building_height": DataTypeNode(
        type_id="dt.raster.building_height",
        theme="building",
        geometry_type="raster",
        description="Building height raster input.",
    ),
    "dt.road.network": DataTypeNode(
        type_id="dt.road.network",
        theme="transportation",
        geometry_type="line",
        description="Road network used as contextual constraint for building fusion.",
    ),
    "dt.waterways.bundle": DataTypeNode(
        type_id="dt.waterways.bundle",
        theme="waterways",
        geometry_type="line",
        description="Prepared waterways line fusion input bundle.",
    ),
    "dt.waterways.fused": DataTypeNode(
        type_id="dt.waterways.fused",
        theme="waterways",
        geometry_type="line",
        description="Fused waterways line output.",
    ),
}


def _algo(
    algo_id: str,
    name: str,
    input_types: list[str],
    output_type: str,
    task_type: str,
    handler_name: str,
    *,
    usage_mode: str = "balanced",
    source_file: str = "",
    alternatives: list[str] | None = None,
) -> AlgorithmNode:
    return AlgorithmNode(
        algo_id=algo_id,
        algo_name=name,
        input_types=input_types,
        output_type=output_type,
        task_type=task_type,
        tool_ref=f"fusion_algorithms:{handler_name}",
        success_rate=0.82,
        accuracy_score=0.86,
        stability_score=0.82,
        usage_mode=usage_mode,
        metadata={
            "runtime_status": "runtime_candidate",
            "algorithm_family": "fusioncode_decomposed",
            "source_file": source_file,
            "handler_name": handler_name,
        },
        alternatives=alternatives or [],
    )


FUSIONCODE_ALGORITHMS = {
    "algo.preprocess.building.source_normalize.v1": _algo(
        "algo.preprocess.building.source_normalize.v1",
        "FusionCode Building Source Normalize",
        ["dt.building.source_set", "dt.building.bundle"],
        "dt.building.normalized_set",
        "building_fusion",
        "_handle_building_source_normalize",
        source_file="algorithm_adapter.py:_parse_geometry_source_paths",
    ),
    "algo.enrich.building.obm_attributes.v1": _algo(
        "algo.enrich.building.obm_attributes.v1",
        "FusionCode OBM Attribute Enrichment",
        ["dt.building.normalized_set"],
        "dt.building.normalized_set",
        "enrichment",
        "_handle_building_obm_attributes",
        source_file="algorithm_core/models/obm_enricher.py",
    ),
    "algo.validate.building.presence_raster.v1": _algo(
        "algo.validate.building.presence_raster.v1",
        "FusionCode Building Presence Raster Validation",
        ["dt.building.normalized_set", "dt.raster.building_presence"],
        "dt.building.presence_validated_set",
        "validation",
        "_handle_building_presence_raster",
        source_file="algorithm_core/models/temporal_validator.py:validate_existence_parallel",
    ),
    "algo.match.building.v8_candidate_graph.v1": _algo(
        "algo.match.building.v8_candidate_graph.v1",
        "FusionCode V8 Building Candidate Graph",
        ["dt.building.presence_validated_set", "dt.building.normalized_set"],
        "dt.building.match_candidate_graph",
        "building_matching",
        "_handle_building_v8_candidate_graph",
        source_file="algorithm_core/models/matching_engine.py:generate_candidate_edges_v8",
    ),
    "algo.match.building.v8_component_solver.v1": _algo(
        "algo.match.building.v8_component_solver.v1",
        "FusionCode V8 Building Component Solver",
        ["dt.building.match_candidate_graph"],
        "dt.building.match_components",
        "building_matching",
        "_handle_building_v8_component_solver",
        source_file="algorithm_core/models/matching_engine.py:process_worker_v8",
    ),
    "algo.fusion.building.cascade_geometry_priority.v1": _algo(
        "algo.fusion.building.cascade_geometry_priority.v1",
        "FusionCode Cascaded Geometry Priority Building Fusion",
        ["dt.building.match_components", "dt.building.normalized_set"],
        "dt.building.fused_raw",
        "building_fusion",
        "_handle_building_cascade_fusion",
        source_file="algorithm_core/models/matching_engine.py:build_fusion_rows",
    ),
    "algo.resolve.building.residual_priority.v1": _algo(
        "algo.resolve.building.residual_priority.v1",
        "FusionCode Residual Priority Conflict Resolution",
        ["dt.building.fused_raw"],
        "dt.building.fused_raw",
        "building_fusion",
        "_handle_building_residual_priority",
        source_file="algorithm_core/models/matching_engine.py:resolve_residual_conflicts_by_priority",
    ),
    "algo.optimize.road.topology_for_buildings.v1": _algo(
        "algo.optimize.road.topology_for_buildings.v1",
        "FusionCode Road Topology For Buildings",
        ["dt.building.fused_raw", "dt.road.network"],
        "dt.building.road_topology_adjusted",
        "building_optimization",
        "_handle_building_road_topology",
        source_file="algorithm_core/models/spatial_optimizer.py:optimize_road_topology",
    ),
    "algo.optimize.building.conflict_graph.v1": _algo(
        "algo.optimize.building.conflict_graph.v1",
        "FusionCode Building Conflict Graph Optimization",
        ["dt.building.road_topology_adjusted", "dt.building.fused_raw"],
        "dt.building.conflict_optimized",
        "building_optimization",
        "_handle_building_conflict_graph",
        source_file="algorithm_core/models/spatial_optimizer.py:run_graph_optimization_v5",
    ),
    "algo.refine.building.post_conflict_shrink.v1": _algo(
        "algo.refine.building.post_conflict_shrink.v1",
        "FusionCode Building Post Conflict Shrink",
        ["dt.building.conflict_optimized"],
        "dt.building.conflict_optimized",
        "building_optimization",
        "_handle_building_post_conflict_shrink",
        source_file="algorithm_core/models/post_conflict_shrink_refiner.py",
    ),
    "algo.refine.building.road_tail.v1": _algo(
        "algo.refine.building.road_tail.v1",
        "FusionCode Road Tail Building Refinement",
        ["dt.building.conflict_optimized", "dt.road.network"],
        "dt.building.conflict_optimized",
        "building_optimization",
        "_handle_building_road_tail",
        source_file="algorithm_core/models/z1r3_conflict.py:road_tail_refinement",
    ),
    "algo.enrich.building.height_from_raster.v1": _algo(
        "algo.enrich.building.height_from_raster.v1",
        "FusionCode Building Height From Raster",
        ["dt.building.conflict_optimized", "dt.raster.building_height"],
        "dt.building.height_enriched",
        "enrichment",
        "_handle_building_height_from_raster",
        source_file="algorithm_core/models/temporal_validator.py:extract_height_parallel",
    ),
    "algo.assess.building.quality_metrics.v1": _algo(
        "algo.assess.building.quality_metrics.v1",
        "FusionCode Building Quality Metrics",
        ["dt.building.height_enriched", "dt.building.conflict_optimized"],
        "dt.building.quality_report",
        "assessment",
        "_handle_building_quality_metrics",
        source_file="algorithm_core/models/spatial_optimizer.py:calculate_metrics",
    ),
    "algo.fusion.building.multi_source.decomposed.v1": _algo(
        "algo.fusion.building.multi_source.decomposed.v1",
        "FusionCode Decomposed Multi-Source Building Fusion",
        ["dt.building.source_set", "dt.building.bundle"],
        "dt.building.fused",
        "building_fusion",
        "_handle_building_multi_source_decomposed",
        usage_mode="throughput",
        source_file="algorithm_core/main.py decomposed sequence",
        alternatives=["algo.fusion.building.safe"],
    ),
    "algo.fusion.road.conflation.v7": _algo(
        "algo.fusion.road.conflation.v7",
        "FusionCode V7 Road Conflation",
        ["dt.road.bundle"],
        "dt.road.fused",
        "road_fusion",
        "_handle_road_conflation_v7",
        source_file="Algorithm/road_fusion_optimized_v7.py",
    ),
    "algo.fusion.waterways.conflation.v7": _algo(
        "algo.fusion.waterways.conflation.v7",
        "FusionCode V7 Waterways Conflation",
        ["dt.waterways.bundle"],
        "dt.waterways.fused",
        "water_fusion",
        "_handle_waterways_conflation_v7",
        source_file="Algorithm/waterways_fusion_v7.py",
    ),
    "algo.fusion.water_polygon.priority_merge.v2": _algo(
        "algo.fusion.water_polygon.priority_merge.v2",
        "FusionCode Water Polygon Priority Merge",
        ["dt.water.bundle"],
        "dt.water.fused",
        "water_fusion",
        "_handle_water_polygon_priority_merge",
        source_file="MapTileTool/FusionTool/lake.py",
    ),
    "algo.fusion.poi.geohash_neighbor_match.v1": _algo(
        "algo.fusion.poi.geohash_neighbor_match.v1",
        "FusionCode POI Geohash Neighbor Match",
        ["dt.poi.bundle"],
        "dt.poi.fused",
        "poi_fusion",
        "_handle_poi_geohash_neighbor_match",
        source_file="MapTileTool/FusionPOI.py",
    ),
    "algo.detect.spatial_conflicts.v1": _algo(
        "algo.detect.spatial_conflicts.v1",
        "FusionCode Spatial Conflict Detection",
        ["dt.building.fused", "dt.water.fused", "dt.road.fused"],
        "dt.building.quality_report",
        "assessment",
        "_handle_spatial_conflicts",
        source_file="MapTileTool/FusionTool/conflict.py",
    ),
}


FUSIONCODE_PARAMETER_SPECS = {
    "algo.validate.building.presence_raster.v1": [
        _param("algo.validate.building.presence_raster.v1", "prob_threshold", default=0.20, min_value=0.0, max_value=1.0, unit="ratio", order=10, tags=["raster", "presence"]),
        _param("algo.validate.building.presence_raster.v1", "search_dist_m", default=4.0, min_value=0.0, unit="meter", order=20, tags=["raster", "recall"]),
        _param("algo.validate.building.presence_raster.v1", "confirmed_score_threshold", default=0.55, min_value=0.0, max_value=1.0, unit="ratio", order=30, tags=["precision"]),
        _param("algo.validate.building.presence_raster.v1", "uncertain_score_threshold", default=0.30, min_value=0.0, max_value=1.0, unit="ratio", order=40, tags=["recall"]),
    ],
    "algo.enrich.building.height_from_raster.v1": [
        _param("algo.enrich.building.height_from_raster.v1", "n_jobs", default=-1, param_type="int", order=10, tags=["performance"]),
        _param("algo.enrich.building.height_from_raster.v1", "height_output_field", default="H_Raster", param_type="string", order=20, tags=["schema"]),
        _param("algo.enrich.building.height_from_raster.v1", "positive_only", default=True, param_type="bool", order=30, tags=["quality"]),
    ],
    "algo.match.building.v8_component_solver.v1": [
        _param("algo.match.building.v8_component_solver.v1", "weak_min_cover", default=0.05, min_value=0.0, max_value=1.0, unit="ratio", order=10, tags=["matching", "recall"]),
        _param("algo.match.building.v8_component_solver.v1", "weak_min_iou", default=0.05, min_value=0.0, max_value=1.0, unit="ratio", order=20, tags=["matching", "recall"]),
        _param("algo.match.building.v8_component_solver.v1", "thresh_1_to_1", default=0.40, min_value=0.0, max_value=1.0, unit="ratio", order=30, tags=["matching"]),
        _param("algo.match.building.v8_component_solver.v1", "thresh_1_to_N", default=0.44, min_value=0.0, max_value=1.0, unit="ratio", order=40, tags=["matching"]),
        _param("algo.match.building.v8_component_solver.v1", "thresh_M_to_N", default=0.47, min_value=0.0, max_value=1.0, unit="ratio", order=50, tags=["matching"]),
        _param("algo.match.building.v8_component_solver.v1", "source_priority_order", default=["MS", "GG", "OSM"], param_type="list", order=60, tags=["lineage", "priority"]),
    ],
    "algo.optimize.building.conflict_graph.v1": [
        _param("algo.optimize.building.conflict_graph.v1", "global_max_shift", default=4.0, min_value=0.0, unit="meter", order=10, tags=["optimization"]),
        _param("algo.optimize.building.conflict_graph.v1", "overlap_delete_threshold", default=0.75, min_value=0.0, max_value=1.0, unit="ratio", order=20, tags=["conflict"]),
        _param("algo.optimize.building.conflict_graph.v1", "road_buffer_width", default=0.1, min_value=0.0, unit="meter", order=30, tags=["road"]),
        _param("algo.optimize.building.conflict_graph.v1", "w_road_expulsion", default=4267.96, min_value=0.0, order=40, tags=["road", "weight"]),
        _param("algo.optimize.building.conflict_graph.v1", "max_outer_iterations", default=3, param_type="int", min_value=1.0, order=50, tags=["performance"]),
    ],
    "algo.refine.building.post_conflict_shrink.v1": [
        _param("algo.refine.building.post_conflict_shrink.v1", "post_shrink_threshold_m2", default=5.0, min_value=0.0, unit="square_meter", order=10, tags=["conflict"]),
        _param("algo.refine.building.post_conflict_shrink.v1", "post_shrink_scale_cap_pct", default=0.05, min_value=0.0, max_value=1.0, unit="ratio", order=20, tags=["geometry"]),
    ],
    "algo.fusion.road.conflation.v7": [
        _param("algo.fusion.road.conflation.v7", "profile", default="balanced", param_type="string", order=5, tags=["profile"]),
        _param("algo.fusion.road.conflation.v7", "target_crs", default="EPSG:32643", param_type="string", order=10, tags=["crs"]),
        _param("algo.fusion.road.conflation.v7", "angle_threshold", default=135, param_type="int", min_value=0.0, max_value=180.0, unit="degree", order=20, tags=["line"]),
        _param("algo.fusion.road.conflation.v7", "max_segment_length", default=800.0, min_value=0.0, unit="meter", order=30, tags=["segmentation"]),
        _param("algo.fusion.road.conflation.v7", "match_buffer_dist", default=20.0, min_value=0.0, unit="meter", order=40, tags=["matching"]),
        _param("algo.fusion.road.conflation.v7", "max_hausdorff", default=15.0, min_value=0.0, unit="meter", order=50, tags=["matching"]),
        _param("algo.fusion.road.conflation.v7", "loose_angle_threshold", default=45.0, min_value=0.0, max_value=180.0, unit="degree", order=60, tags=["matching"]),
        _param("algo.fusion.road.conflation.v7", "min_len_similarity", default=0.05, min_value=0.0, max_value=1.0, unit="ratio", order=70, tags=["matching"]),
        _param("algo.fusion.road.conflation.v7", "min_supplement_coverage_for_matched", default=0.8, min_value=0.0, max_value=1.0, unit="ratio", order=80, tags=["matching"]),
        _param("algo.fusion.road.conflation.v7", "preserve_matched_supplement_residuals", default=True, param_type="bool", order=90, tags=["residual"]),
        _param("algo.fusion.road.conflation.v7", "min_residual_length", default=10.0, min_value=0.0, unit="meter", order=100, tags=["residual"]),
        _param("algo.fusion.road.conflation.v7", "duplicate_buffer_dist", default=10.0, min_value=0.0, unit="meter", order=110, tags=["dedupe"]),
        _param("algo.fusion.road.conflation.v7", "duplicate_coverage_threshold", default=0.92, min_value=0.0, max_value=1.0, unit="ratio", order=120, tags=["dedupe"]),
        _param("algo.fusion.road.conflation.v7", "near_base_return_coverage_threshold", default=0.85, min_value=0.0, max_value=1.0, unit="ratio", order=130, tags=["pruning"]),
        _param("algo.fusion.road.conflation.v7", "crossing_coverage_threshold", default=0.82, min_value=0.0, max_value=1.0, unit="ratio", order=140, tags=["pruning"]),
        _param("algo.fusion.road.conflation.v7", "cleanup_mode", default="quality", param_type="string", order=150, tags=["cleanup"]),
        _param("algo.fusion.road.conflation.v7", "output_crs", default=None, param_type="string", order=160, tags=["crs"]),
    ],
    "algo.fusion.waterways.conflation.v7": [
        _param("algo.fusion.waterways.conflation.v7", "target_crs", default="EPSG:32643", param_type="string", order=10, tags=["crs"]),
        _param("algo.fusion.waterways.conflation.v7", "angle_threshold", default=135, param_type="int", min_value=0.0, max_value=180.0, unit="degree", order=20, tags=["line"]),
        _param("algo.fusion.waterways.conflation.v7", "max_segment_length", default=1000.0, min_value=0.0, unit="meter", order=30, tags=["segmentation"]),
        _param("algo.fusion.waterways.conflation.v7", "match_buffer_dist", default=25.0, min_value=0.0, unit="meter", order=40, tags=["matching"]),
        _param("algo.fusion.waterways.conflation.v7", "max_hausdorff", default=20.0, min_value=0.0, unit="meter", order=50, tags=["matching"]),
        _param("algo.fusion.waterways.conflation.v7", "loose_angle_threshold", default=50.0, min_value=0.0, max_value=180.0, unit="degree", order=60, tags=["matching"]),
        _param("algo.fusion.waterways.conflation.v7", "min_len_similarity", default=0.03, min_value=0.0, max_value=1.0, unit="ratio", order=70, tags=["matching"]),
        _param("algo.fusion.waterways.conflation.v7", "min_supplement_coverage_for_matched", default=0.8, min_value=0.0, max_value=1.0, unit="ratio", order=80, tags=["matching"]),
        _param("algo.fusion.waterways.conflation.v7", "min_residual_length", default=20.0, min_value=0.0, unit="meter", order=90, tags=["residual"]),
        _param("algo.fusion.waterways.conflation.v7", "duplicate_buffer_dist", default=12.0, min_value=0.0, unit="meter", order=100, tags=["dedupe"]),
        _param("algo.fusion.waterways.conflation.v7", "near_base_return_corridor_dist", default=15.0, min_value=0.0, unit="meter", order=110, tags=["pruning"]),
        _param("algo.fusion.waterways.conflation.v7", "crossing_corridor_dist", default=15.0, min_value=0.0, unit="meter", order=120, tags=["pruning"]),
        _param("algo.fusion.waterways.conflation.v7", "cleanup_mode", default="fast", param_type="string", order=130, tags=["cleanup"]),
        _param("algo.fusion.waterways.conflation.v7", "output_crs", default=None, param_type="string", order=140, tags=["crs"]),
    ],
    "algo.fusion.water_polygon.priority_merge.v2": [
        _param("algo.fusion.water_polygon.priority_merge.v2", "overlap_threshold", default=0.1, min_value=0.0, max_value=1.0, unit="ratio", order=10, tags=["polygon"]),
    ],
    "algo.fusion.poi.geohash_neighbor_match.v1": [
        _param("algo.fusion.poi.geohash_neighbor_match.v1", "neighbor_rings", default=1, param_type="int", min_value=0.0, order=10, tags=["geohash"]),
        _param("algo.fusion.poi.geohash_neighbor_match.v1", "name_similarity_threshold", default=0.75, min_value=0.0, max_value=1.0, unit="ratio", order=20, tags=["name"]),
    ],
}


FUSIONCODE_WORKFLOW_PATTERNS = [
    WorkflowPatternNode(
        pattern_id="wp.building.drs4br.decomposed.v1",
        pattern_name="FusionCode DRS4BR Decomposed Building Fusion",
        job_type=JobType.building,
        disaster_types=["flood", "earthquake", "typhoon", "generic"],
        success_rate=0.84,
        metadata={
            "version": "1.0.0",
            "runtime_status": "runtime_candidate",
            "algorithm_family": "fusioncode_decomposed",
            "expands_to_primitives": "true",
        },
        steps=[
            PatternStep(1, "source_normalize", "algo.preprocess.building.source_normalize.v1", "dt.building.source_set", "dt.building.normalized_set"),
            PatternStep(2, "obm_attributes", "algo.enrich.building.obm_attributes.v1", "dt.building.normalized_set", "dt.building.normalized_set", depends_on=[1], is_optional=True),
            PatternStep(3, "presence_raster", "algo.validate.building.presence_raster.v1", "dt.building.normalized_set", "dt.building.presence_validated_set", depends_on=[1], is_optional=True),
            PatternStep(4, "v8_candidate_graph", "algo.match.building.v8_candidate_graph.v1", "dt.building.presence_validated_set", "dt.building.match_candidate_graph", depends_on=[3]),
            PatternStep(5, "v8_component_solver", "algo.match.building.v8_component_solver.v1", "dt.building.match_candidate_graph", "dt.building.match_components", depends_on=[4]),
            PatternStep(6, "cascade_geometry_priority", "algo.fusion.building.cascade_geometry_priority.v1", "dt.building.match_components", "dt.building.fused_raw", depends_on=[5]),
            PatternStep(7, "residual_priority", "algo.resolve.building.residual_priority.v1", "dt.building.fused_raw", "dt.building.fused_raw", depends_on=[6]),
            PatternStep(8, "road_topology", "algo.optimize.road.topology_for_buildings.v1", "dt.building.fused_raw", "dt.building.road_topology_adjusted", depends_on=[7], is_optional=True),
            PatternStep(9, "conflict_graph", "algo.optimize.building.conflict_graph.v1", "dt.building.road_topology_adjusted", "dt.building.conflict_optimized", depends_on=[8]),
            PatternStep(10, "post_conflict_shrink", "algo.refine.building.post_conflict_shrink.v1", "dt.building.conflict_optimized", "dt.building.conflict_optimized", depends_on=[9], is_optional=True),
            PatternStep(11, "road_tail", "algo.refine.building.road_tail.v1", "dt.building.conflict_optimized", "dt.building.conflict_optimized", depends_on=[10], is_optional=True),
            PatternStep(12, "height_from_raster", "algo.enrich.building.height_from_raster.v1", "dt.building.conflict_optimized", "dt.building.height_enriched", depends_on=[11], is_optional=True),
            PatternStep(13, "quality_metrics", "algo.assess.building.quality_metrics.v1", "dt.building.height_enriched", "dt.building.quality_report", depends_on=[12]),
        ],
    ),
    WorkflowPatternNode(
        pattern_id="wp.road.fusioncode.conflation.v7",
        pattern_name="FusionCode V7 Road Conflation",
        job_type=JobType.road,
        disaster_types=["flood", "earthquake", "typhoon", "generic"],
        success_rate=0.86,
        metadata={"version": "1.0.0", "runtime_status": "runtime_candidate", "algorithm_family": "fusioncode_decomposed"},
        steps=[
            PatternStep(1, "road_conflation_v7", "algo.fusion.road.conflation.v7", "dt.road.bundle", "dt.road.fused"),
        ],
    ),
    WorkflowPatternNode(
        pattern_id="wp.waterways.fusioncode.conflation.v7",
        pattern_name="FusionCode V7 Waterways Conflation",
        job_type=JobType.water,
        disaster_types=["flood", "generic"],
        success_rate=0.82,
        metadata={
            "version": "1.0.0",
            "runtime_status": "runtime_candidate",
            "algorithm_family": "fusioncode_decomposed",
            "water_semantics": "waterways_line",
            "input_strategy": "task_driven_auto_supported",
            "source_family": "catalog_waterways_bundle",
        },
        steps=[
            PatternStep(1, "waterways_conflation_v7", "algo.fusion.waterways.conflation.v7", "dt.waterways.bundle", "dt.waterways.fused", "catalog.flood.waterways"),
        ],
    ),
    WorkflowPatternNode(
        pattern_id="wp.water_polygon.fusioncode.priority_merge.v2",
        pattern_name="FusionCode Water Polygon Priority Merge",
        job_type=JobType.water,
        disaster_types=["flood", "generic"],
        success_rate=0.83,
        metadata={
            "version": "2.0.0",
            "runtime_status": "runtime_candidate",
            "algorithm_family": "fusioncode_decomposed",
            "water_semantics": "polygon",
            "input_strategy": "task_driven_auto_supported",
            "source_family": "catalog_water_bundle",
        },
        steps=[
            PatternStep(1, "water_polygon_priority_merge", "algo.fusion.water_polygon.priority_merge.v2", "dt.water.bundle", "dt.water.fused", "catalog.flood.water"),
        ],
    ),
    WorkflowPatternNode(
        pattern_id="wp.poi.fusioncode.geohash_priority.v1",
        pattern_name="FusionCode POI Geohash Priority Fusion",
        job_type=JobType.poi,
        disaster_types=["generic"],
        success_rate=0.8,
        metadata={"version": "1.0.0", "runtime_status": "runtime_candidate", "algorithm_family": "fusioncode_decomposed"},
        steps=[
            PatternStep(1, "poi_geohash_neighbor_match", "algo.fusion.poi.geohash_neighbor_match.v1", "dt.poi.bundle", "dt.poi.fused"),
        ],
    ),
]
