from __future__ import annotations

from typing import Dict, List

from schemas.fusion import JobType

from kg.models import (
    AlgorithmNode,
    AlgorithmParameterSpec,
    DataSourceNode,
    DataTypeNode,
    OutputSchemaPolicy,
    PatternStep,
    WorkflowPatternNode,
)


DATA_TYPES: Dict[str, DataTypeNode] = {
    "dt.raw.vector": DataTypeNode(
        type_id="dt.raw.vector",
        theme="generic",
        geometry_type="mixed",
        description="Uploaded raw vector bundle.",
    ),
    "dt.building.bundle": DataTypeNode(
        type_id="dt.building.bundle",
        theme="building",
        geometry_type="polygon",
        description="Prepared building fusion input bundle.",
    ),
    "dt.road.bundle": DataTypeNode(
        type_id="dt.road.bundle",
        theme="transportation",
        geometry_type="line",
        description="Prepared road fusion input bundle.",
    ),
    "dt.building.fused": DataTypeNode(
        type_id="dt.building.fused",
        theme="building",
        geometry_type="polygon",
        description="Fused building output.",
    ),
    "dt.road.fused": DataTypeNode(
        type_id="dt.road.fused",
        theme="transportation",
        geometry_type="line",
        description="Fused road output.",
    ),
}


ALGORITHMS: Dict[str, AlgorithmNode] = {
    "algo.fusion.building.v1": AlgorithmNode(
        algo_id="algo.fusion.building.v1",
        algo_name="Building Fusion Legacy",
        input_types=["dt.building.bundle"],
        output_type="dt.building.fused",
        task_type="building_fusion",
        tool_ref="adapters.building_adapter:run_building_fusion",
        success_rate=0.92,
        accuracy_score=0.89,
        stability_score=0.74,
        usage_mode="throughput",
        metadata={
            "selection_profile": "primary",
            "evidence_basis": "legacy_default_runtime",
        },
        alternatives=["algo.fusion.building.safe"],
    ),
    "algo.fusion.building.safe": AlgorithmNode(
        algo_id="algo.fusion.building.safe",
        algo_name="Building Fusion Safe Fallback",
        input_types=["dt.building.bundle"],
        output_type="dt.building.fused",
        task_type="building_fusion",
        tool_ref="adapters.building_adapter:run_building_fusion",
        success_rate=0.75,
        accuracy_score=0.79,
        stability_score=0.91,
        usage_mode="conservative",
        metadata={
            "selection_profile": "fallback",
            "evidence_basis": "conservative_thresholds",
        },
        alternatives=["algo.fusion.building.v1"],
    ),
    "algo.fusion.road.v1": AlgorithmNode(
        algo_id="algo.fusion.road.v1",
        algo_name="Road Fusion Legacy",
        input_types=["dt.road.bundle"],
        output_type="dt.road.fused",
        task_type="road_fusion",
        tool_ref="adapters.road_adapter:run_road_fusion",
        success_rate=0.9,
        accuracy_score=0.86,
        stability_score=0.72,
        usage_mode="throughput",
        metadata={
            "selection_profile": "primary",
            "evidence_basis": "legacy_default_runtime",
        },
        alternatives=["algo.fusion.road.safe"],
    ),
    "algo.fusion.road.safe": AlgorithmNode(
        algo_id="algo.fusion.road.safe",
        algo_name="Road Fusion Safe Fallback",
        input_types=["dt.road.bundle"],
        output_type="dt.road.fused",
        task_type="road_fusion",
        tool_ref="adapters.road_adapter:run_road_fusion",
        success_rate=0.72,
        accuracy_score=0.77,
        stability_score=0.9,
        usage_mode="conservative",
        metadata={
            "selection_profile": "fallback",
            "evidence_basis": "conservative_thresholds",
        },
        alternatives=["algo.fusion.road.v1"],
    ),
    "algo.transform.raw_to_building_bundle": AlgorithmNode(
        algo_id="algo.transform.raw_to_building_bundle",
        algo_name="Raw Vector to Building Bundle",
        input_types=["dt.raw.vector"],
        output_type="dt.building.bundle",
        task_type="transform",
        tool_ref="builtin:transform",
        success_rate=0.98,
        accuracy_score=0.97,
        stability_score=0.96,
        usage_mode="normalization",
        metadata={
            "selection_profile": "preparation",
            "evidence_basis": "deterministic_transform",
        },
    ),
    "algo.transform.raw_to_road_bundle": AlgorithmNode(
        algo_id="algo.transform.raw_to_road_bundle",
        algo_name="Raw Vector to Road Bundle",
        input_types=["dt.raw.vector"],
        output_type="dt.road.bundle",
        task_type="transform",
        tool_ref="builtin:transform",
        success_rate=0.98,
        accuracy_score=0.97,
        stability_score=0.96,
        usage_mode="normalization",
        metadata={
            "selection_profile": "preparation",
            "evidence_basis": "deterministic_transform",
        },
    ),
}

PARAMETER_SPECS: Dict[str, List[AlgorithmParameterSpec]] = {
    # Building fusion parameters are derived from legacy adapter semantics:
    # - match similarity threshold: label=1 when similarity > threshold
    # - one-to-one thresholds: sim_area/sim_shape/sim_overlap must each be >= threshold
    "algo.fusion.building.v1": [
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.building.v1.match_similarity_threshold",
            algo_id="algo.fusion.building.v1",
            key="match_similarity_threshold",
            label="Match Similarity Threshold",
            param_type="float",
            default=0.3,
            min_value=0.0,
            max_value=1.0,
            unit="ratio",
            description="Pairs with similarity > this value are treated as matched (legacy label=1).",
            required=False,
            tunable=True,
            optimization_tags=["precision", "recall", "matching"],
            order=10,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.building.v1.one_to_one_min_area_similarity",
            algo_id="algo.fusion.building.v1",
            key="one_to_one_min_area_similarity",
            label="One-to-One Min Area Similarity",
            param_type="float",
            default=0.3,
            min_value=0.0,
            max_value=1.0,
            unit="ratio",
            description="For 1:1 matches, sim_area must be >= this value to fuse as one-to-one.",
            required=False,
            tunable=True,
            optimization_tags=["precision", "stability", "shape_consistency"],
            order=20,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.building.v1.one_to_one_min_shape_similarity",
            algo_id="algo.fusion.building.v1",
            key="one_to_one_min_shape_similarity",
            label="One-to-One Min Shape Similarity",
            param_type="float",
            default=0.3,
            min_value=0.0,
            max_value=1.0,
            unit="ratio",
            description="For 1:1 matches, sim_shape must be >= this value to fuse as one-to-one.",
            required=False,
            tunable=True,
            optimization_tags=["precision", "stability", "shape_consistency"],
            order=30,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.building.v1.one_to_one_min_overlap_similarity",
            algo_id="algo.fusion.building.v1",
            key="one_to_one_min_overlap_similarity",
            label="One-to-One Min Overlap Similarity",
            param_type="float",
            default=0.3,
            min_value=0.0,
            max_value=1.0,
            unit="ratio",
            description="For 1:1 matches, sim_overlap must be >= this value to fuse as one-to-one.",
            required=False,
            tunable=True,
            optimization_tags=["precision", "recall", "overlap_consistency"],
            order=40,
        ),
    ],
    "algo.fusion.building.safe": [
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.building.safe.match_similarity_threshold",
            algo_id="algo.fusion.building.safe",
            key="match_similarity_threshold",
            label="Match Similarity Threshold",
            param_type="float",
            default=0.4,
            min_value=0.0,
            max_value=1.0,
            unit="ratio",
            description="Conservative match threshold for safe mode.",
            required=False,
            tunable=True,
            optimization_tags=["precision", "stability", "matching"],
            order=10,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.building.safe.one_to_one_min_area_similarity",
            algo_id="algo.fusion.building.safe",
            key="one_to_one_min_area_similarity",
            label="One-to-One Min Area Similarity",
            param_type="float",
            default=0.45,
            min_value=0.0,
            max_value=1.0,
            unit="ratio",
            description="Conservative area similarity threshold for safe mode.",
            required=False,
            tunable=True,
            optimization_tags=["precision", "stability", "shape_consistency"],
            order=20,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.building.safe.one_to_one_min_shape_similarity",
            algo_id="algo.fusion.building.safe",
            key="one_to_one_min_shape_similarity",
            label="One-to-One Min Shape Similarity",
            param_type="float",
            default=0.45,
            min_value=0.0,
            max_value=1.0,
            unit="ratio",
            description="Conservative shape similarity threshold for safe mode.",
            required=False,
            tunable=True,
            optimization_tags=["precision", "stability", "shape_consistency"],
            order=30,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.building.safe.one_to_one_min_overlap_similarity",
            algo_id="algo.fusion.building.safe",
            key="one_to_one_min_overlap_similarity",
            label="One-to-One Min Overlap Similarity",
            param_type="float",
            default=0.4,
            min_value=0.0,
            max_value=1.0,
            unit="ratio",
            description="Conservative one-to-one overlap threshold for safe mode.",
            required=False,
            tunable=True,
            optimization_tags=["precision", "stability", "overlap_consistency"],
            order=40,
        ),
    ],
    # Road fusion parameters are derived from legacy algorithm constants and adapter defaults:
    # - ANGLE_THRESHOLD / SNAP_TOLERANCE / BUFFER_DIST / MAX_HAUSDORFF in Algorithm/line.py
    # - dedupe buffer_distance default in adapters/road_adapter.py
    "algo.fusion.road.v1": [
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.road.v1.angle_threshold_deg",
            algo_id="algo.fusion.road.v1",
            key="angle_threshold_deg",
            label="Split Angle Threshold",
            param_type="int",
            default=135,
            min_value=0.0,
            max_value=180.0,
            unit="deg",
            description="Split lines at sharp turns: angles below this threshold trigger a split.",
            required=False,
            tunable=True,
            optimization_tags=["stability", "segmentation"],
            order=10,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.road.v1.snap_tolerance_m",
            algo_id="algo.fusion.road.v1",
            key="snap_tolerance_m",
            label="Snap Tolerance",
            param_type="float",
            default=1.0,
            min_value=0.0,
            max_value=10.0,
            unit="m",
            description="Endpoint snap tolerance used when normalizing line endpoints.",
            required=False,
            tunable=True,
            optimization_tags=["stability", "topology"],
            order=20,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.road.v1.match_buffer_m",
            algo_id="algo.fusion.road.v1",
            key="match_buffer_m",
            label="Match Buffer Distance",
            param_type="float",
            default=20.0,
            min_value=0.0,
            max_value=100.0,
            unit="m",
            description="Buffer radius for candidate matching between OSM and reference lines.",
            required=False,
            tunable=True,
            optimization_tags=["recall", "matching"],
            order=30,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.road.v1.max_hausdorff_m",
            algo_id="algo.fusion.road.v1",
            key="max_hausdorff_m",
            label="Max Hausdorff Distance",
            param_type="float",
            default=15.0,
            min_value=0.0,
            max_value=100.0,
            unit="m",
            description="Maximum Hausdorff distance allowed to consider two lines as a match.",
            required=False,
            tunable=True,
            optimization_tags=["precision", "stability", "matching"],
            order=40,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.road.v1.dedupe_buffer_m",
            algo_id="algo.fusion.road.v1",
            key="dedupe_buffer_m",
            label="Dedupe Buffer Distance",
            param_type="float",
            default=15.0,
            min_value=0.0,
            max_value=100.0,
            unit="m",
            description="Buffer distance used during post-fusion deduplication.",
            required=False,
            tunable=True,
            optimization_tags=["stability", "deduplication"],
            order=50,
        ),
    ],
    "algo.fusion.road.safe": [
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.road.safe.angle_threshold_deg",
            algo_id="algo.fusion.road.safe",
            key="angle_threshold_deg",
            label="Split Angle Threshold",
            param_type="int",
            default=120,
            min_value=0.0,
            max_value=180.0,
            unit="deg",
            description="Conservative split angle threshold for safe mode.",
            required=False,
            tunable=True,
            optimization_tags=["stability", "segmentation"],
            order=10,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.road.safe.snap_tolerance_m",
            algo_id="algo.fusion.road.safe",
            key="snap_tolerance_m",
            label="Snap Tolerance",
            param_type="float",
            default=0.75,
            min_value=0.0,
            max_value=10.0,
            unit="m",
            description="Conservative endpoint snap tolerance for safe mode.",
            required=False,
            tunable=True,
            optimization_tags=["stability", "topology"],
            order=20,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.road.safe.match_buffer_m",
            algo_id="algo.fusion.road.safe",
            key="match_buffer_m",
            label="Match Buffer Distance",
            param_type="float",
            default=15.0,
            min_value=0.0,
            max_value=100.0,
            unit="m",
            description="Conservative match buffer for safe mode.",
            required=False,
            tunable=True,
            optimization_tags=["precision", "matching"],
            order=30,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.road.safe.max_hausdorff_m",
            algo_id="algo.fusion.road.safe",
            key="max_hausdorff_m",
            label="Max Hausdorff Distance",
            param_type="float",
            default=10.0,
            min_value=0.0,
            max_value=100.0,
            unit="m",
            description="Conservative Hausdorff threshold for safe mode.",
            required=False,
            tunable=True,
            optimization_tags=["precision", "stability", "matching"],
            order=40,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.road.safe.dedupe_buffer_m",
            algo_id="algo.fusion.road.safe",
            key="dedupe_buffer_m",
            label="Dedupe Buffer Distance",
            param_type="float",
            default=12.0,
            min_value=0.0,
            max_value=100.0,
            unit="m",
            description="Conservative dedupe buffer for safe mode.",
            required=False,
            tunable=True,
            optimization_tags=["stability", "deduplication"],
            order=50,
        ),
    ],
}


WORKFLOW_PATTERNS: List[WorkflowPatternNode] = [
    WorkflowPatternNode(
        pattern_id="wp.flood.building.default",
        pattern_name="Flood Building Fusion",
        job_type=JobType.building,
        disaster_types=["flood", "typhoon", "generic"],
        success_rate=0.88,
        metadata={
            "version": "1.0.0",
            "runtime_status": "runtime_candidate",
            "scenario_focus": "flood",
            "strategy": "throughput",
        },
        steps=[
            PatternStep(
                order=1,
                name="building_fusion",
                algorithm_id="algo.fusion.building.v1",
                input_data_type="dt.building.bundle",
                output_data_type="dt.building.fused",
                data_source_id="upload.bundle",
            )
        ],
    ),
    WorkflowPatternNode(
        pattern_id="wp.flood.building.safe",
        pattern_name="Flood Building Fusion Safe Route",
        job_type=JobType.building,
        disaster_types=["flood", "generic"],
        success_rate=0.82,
        metadata={
            "version": "1.0.0",
            "runtime_status": "runtime_candidate",
            "scenario_focus": "flood",
            "mode": "safe",
            "strategy": "conservative",
        },
        steps=[
            PatternStep(
                order=1,
                name="building_fusion_safe",
                algorithm_id="algo.fusion.building.safe",
                input_data_type="dt.building.bundle",
                output_data_type="dt.building.fused",
                data_source_id="upload.bundle",
            )
        ],
    ),
    WorkflowPatternNode(
        pattern_id="wp.earthquake.building.default",
        pattern_name="Earthquake Building Fusion",
        job_type=JobType.building,
        disaster_types=["earthquake"],
        success_rate=0.91,
        metadata={
            "version": "1.0.0",
            "runtime_status": "runtime_candidate",
            "scenario_focus": "earthquake",
            "strategy": "throughput",
        },
        steps=[
            PatternStep(
                order=1,
                name="building_fusion_earthquake",
                algorithm_id="algo.fusion.building.v1",
                input_data_type="dt.building.bundle",
                output_data_type="dt.building.fused",
                data_source_id="upload.bundle",
            )
        ],
    ),
    WorkflowPatternNode(
        pattern_id="wp.earthquake.building.safe",
        pattern_name="Earthquake Building Fusion Safe Route",
        job_type=JobType.building,
        disaster_types=["earthquake"],
        success_rate=0.85,
        metadata={
            "version": "1.0.0",
            "runtime_status": "runtime_candidate",
            "scenario_focus": "earthquake",
            "mode": "safe",
            "strategy": "conservative",
        },
        steps=[
            PatternStep(
                order=1,
                name="building_fusion_safe",
                algorithm_id="algo.fusion.building.safe",
                input_data_type="dt.building.bundle",
                output_data_type="dt.building.fused",
                data_source_id="upload.bundle",
            )
        ],
    ),
    WorkflowPatternNode(
        pattern_id="wp.flood.road.default",
        pattern_name="Flood Road Fusion",
        job_type=JobType.road,
        disaster_types=["flood", "earthquake", "generic"],
        success_rate=0.86,
        metadata={
            "version": "1.0.0",
            "runtime_status": "runtime_candidate",
            "scenario_focus": "flood",
            "strategy": "throughput",
        },
        steps=[
            PatternStep(
                order=1,
                name="road_fusion",
                algorithm_id="algo.fusion.road.v1",
                input_data_type="dt.road.bundle",
                output_data_type="dt.road.fused",
                data_source_id="upload.bundle",
            )
        ],
    ),
    WorkflowPatternNode(
        pattern_id="wp.flood.road.safe",
        pattern_name="Flood Road Fusion Safe Route",
        job_type=JobType.road,
        disaster_types=["flood", "generic"],
        success_rate=0.81,
        metadata={
            "version": "1.0.0",
            "runtime_status": "runtime_candidate",
            "scenario_focus": "flood",
            "mode": "safe",
            "strategy": "conservative",
        },
        steps=[
            PatternStep(
                order=1,
                name="road_fusion_safe",
                algorithm_id="algo.fusion.road.safe",
                input_data_type="dt.road.bundle",
                output_data_type="dt.road.fused",
                data_source_id="upload.bundle",
            )
        ],
    ),
    WorkflowPatternNode(
        pattern_id="wp.typhoon.road.default",
        pattern_name="Typhoon Road Fusion",
        job_type=JobType.road,
        disaster_types=["typhoon"],
        success_rate=0.9,
        metadata={
            "version": "1.0.0",
            "runtime_status": "runtime_candidate",
            "scenario_focus": "typhoon",
            "strategy": "throughput",
        },
        steps=[
            PatternStep(
                order=1,
                name="road_fusion_typhoon",
                algorithm_id="algo.fusion.road.v1",
                input_data_type="dt.road.bundle",
                output_data_type="dt.road.fused",
                data_source_id="upload.bundle",
            )
        ],
    ),
    WorkflowPatternNode(
        pattern_id="wp.typhoon.road.safe",
        pattern_name="Typhoon Road Fusion Safe Route",
        job_type=JobType.road,
        disaster_types=["typhoon"],
        success_rate=0.84,
        metadata={
            "version": "1.0.0",
            "runtime_status": "runtime_candidate",
            "scenario_focus": "typhoon",
            "mode": "safe",
            "strategy": "conservative",
        },
        steps=[
            PatternStep(
                order=1,
                name="road_fusion_safe",
                algorithm_id="algo.fusion.road.safe",
                input_data_type="dt.road.bundle",
                output_data_type="dt.road.fused",
                data_source_id="upload.bundle",
            )
        ],
    ),
]


DATA_SOURCES: List[DataSourceNode] = [
    DataSourceNode(
        source_id="upload.bundle",
        source_name="Uploaded Bundle",
        supported_types=["dt.building.bundle", "dt.road.bundle", "dt.raw.vector"],
        disaster_types=["generic", "flood", "earthquake", "typhoon"],
        quality_score=1.0,
        source_kind="local_upload",
        quality_tier="operator_provided",
        freshness_category="request_bound",
        freshness_hours=0,
        freshness_score=1.0,
        supported_job_types=["building", "road"],
        supported_geometry_types=["mixed", "polygon", "line"],
        metadata={"kind": "local"},
    ),
    DataSourceNode(
        source_id="catalog.flood.building",
        source_name="Flood Building Catalog",
        supported_types=["dt.building.bundle"],
        disaster_types=["flood", "generic"],
        quality_score=0.86,
        source_kind="catalog",
        quality_tier="curated",
        freshness_category="event_snapshot",
        freshness_hours=72,
        freshness_score=0.74,
        supported_job_types=["building"],
        supported_geometry_types=["polygon"],
        metadata={"kind": "catalog", "priority": 2},
    ),
    DataSourceNode(
        source_id="catalog.earthquake.building",
        source_name="Earthquake Building Catalog",
        supported_types=["dt.building.bundle"],
        disaster_types=["earthquake", "generic"],
        quality_score=0.88,
        source_kind="catalog",
        quality_tier="curated",
        freshness_category="event_snapshot",
        freshness_hours=96,
        freshness_score=0.71,
        supported_job_types=["building"],
        supported_geometry_types=["polygon"],
        metadata={"kind": "catalog", "priority": 2},
    ),
    DataSourceNode(
        source_id="catalog.earthquake.road",
        source_name="Earthquake Road Catalog",
        supported_types=["dt.road.bundle"],
        disaster_types=["earthquake", "generic"],
        quality_score=0.84,
        source_kind="catalog",
        quality_tier="curated",
        freshness_category="event_snapshot",
        freshness_hours=96,
        freshness_score=0.69,
        supported_job_types=["road"],
        supported_geometry_types=["line"],
        metadata={"kind": "catalog", "priority": 2},
    ),
    DataSourceNode(
        source_id="catalog.typhoon.road",
        source_name="Typhoon Road Catalog",
        supported_types=["dt.road.bundle"],
        disaster_types=["typhoon", "generic"],
        quality_score=0.87,
        source_kind="catalog",
        quality_tier="curated",
        freshness_category="event_snapshot",
        freshness_hours=48,
        freshness_score=0.78,
        supported_job_types=["road"],
        supported_geometry_types=["line"],
        metadata={"kind": "catalog", "priority": 2},
    ),
]


OUTPUT_SCHEMA_POLICIES: Dict[str, OutputSchemaPolicy] = {
    "dt.building.fused": OutputSchemaPolicy(
        policy_id="osp.building.fused.v1",
        output_type="dt.building.fused",
        job_type=JobType.building,
        retention_mode="preserve_listed",
        required_fields=["geometry"],
        optional_fields=[
            "osm_id",
            "fclass",
            "name",
            "type",
            "longitude",
            "latitude",
            "area_in_me",
            "confidence",
        ],
        rename_hints={
            "geometry_x": "geometry",
            "geometry_y": "geometry",
        },
        compatibility_basis="field_names",
        metadata={
            "policy_scope": "current_runtime",
            "notes": "Expose stable fused building columns without changing adapter behavior.",
        },
    ),
    "dt.road.fused": OutputSchemaPolicy(
        policy_id="osp.road.fused.v1",
        output_type="dt.road.fused",
        job_type=JobType.road,
        retention_mode="preserve_listed",
        required_fields=["geometry"],
        optional_fields=["osm_id", "FID_1", "fclass"],
        rename_hints={},
        compatibility_basis="field_names",
        metadata={
            "policy_scope": "current_runtime",
            "notes": "Road output schema remains metadata-only until explicit output policy execution is added.",
        },
    ),
}


CAN_TRANSFORM_TO: Dict[str, List[str]] = {
    "dt.raw.vector": ["dt.building.bundle", "dt.road.bundle"],
}
