from __future__ import annotations

from typing import Dict, List

from schemas.fusion import JobType

from kg.models import (
    AlgorithmNode,
    AlgorithmParameterSpec,
    DataNeedNode,
    DataSourceNode,
    DataTypeNode,
    OutputSchemaPolicy,
    OutputRequirementNode,
    PatternStep,
    QoSPolicyNode,
    RepairStrategyNode,
    ScenarioProfileNode,
    TaskBundleNode,
    TaskNode,
    WorkflowPatternNode,
)
from kg.source_catalog import build_data_sources


def _claim_state_to_runtime_status(claim_state: str) -> str:
    normalized = claim_state.strip().lower()
    if normalized == "reservation_only":
        return "reservation_only"
    if normalized in {"runtime_supported", "bounded_supported", "research_utility"}:
        return "runtime_candidate"
    return "runtime_candidate"


def _closure_metadata(*, claim_state: str, runtime_role: str, **extra: object) -> Dict[str, object]:
    return {
        "claim_state": claim_state,
        "runtime_status": _claim_state_to_runtime_status(claim_state),
        "runtime_role": runtime_role,
        **extra,
    }


DATA_TYPES: Dict[str, DataTypeNode] = {
    "dt.raw.vector": DataTypeNode(
        type_id="dt.raw.vector",
        theme="generic",
        geometry_type="mixed",
        description="Uploaded raw vector bundle.",
    ),
    "dt.building.bundle": DataTypeNode(
        type_id="dt.building.bundle",
        theme="building",
        geometry_type="polygon",
        description="Prepared building fusion input bundle.",
    ),
    "dt.road.bundle": DataTypeNode(
        type_id="dt.road.bundle",
        theme="transportation",
        geometry_type="line",
        description="Prepared road fusion input bundle.",
    ),
    "dt.trajectory.raw": DataTypeNode(
        type_id="dt.trajectory.raw",
        theme="transportation",
        geometry_type="line",
        description="Reserved pretransform trajectory observations for future road candidate generation.",
    ),
    "dt.road.candidate": DataTypeNode(
        type_id="dt.road.candidate",
        theme="transportation",
        geometry_type="line",
        description="Reserved intermediate road candidates derived from trajectory pretransform.",
    ),
    "dt.water.bundle": DataTypeNode(
        type_id="dt.water.bundle",
        theme="water",
        geometry_type="polygon",
        description="Prepared water polygon fusion input bundle.",
    ),
    "dt.waterways.bundle": DataTypeNode(
        type_id="dt.waterways.bundle",
        theme="waterways",
        geometry_type="line",
        description="Prepared waterways line fusion input bundle.",
    ),
    "dt.poi.bundle": DataTypeNode(
        type_id="dt.poi.bundle",
        theme="poi",
        geometry_type="point",
        description="Prepared point-of-interest fusion input bundle.",
    ),
    "dt.building.source_set": DataTypeNode(
        type_id="dt.building.source_set",
        theme="building",
        geometry_type="mixed",
        description="Reserved multi-source building input set for future fusion algorithms.",
    ),
    "dt.raster.building_presence": DataTypeNode(
        type_id="dt.raster.building_presence",
        theme="building",
        geometry_type="raster",
        description="Reserved building-presence raster input.",
    ),
    "dt.partition.tile_manifest": DataTypeNode(
        type_id="dt.partition.tile_manifest",
        theme="runtime",
        geometry_type="none",
        description="Reserved deterministic AOI tile partition manifest.",
    ),
    "dt.building.fused": DataTypeNode(
        type_id="dt.building.fused",
        theme="building",
        geometry_type="polygon",
        description="Fused building output.",
    ),
    "dt.road.fused": DataTypeNode(
        type_id="dt.road.fused",
        theme="transportation",
        geometry_type="line",
        description="Fused road output.",
    ),
    "dt.water.fused": DataTypeNode(
        type_id="dt.water.fused",
        theme="water",
        geometry_type="polygon",
        description="Fused water polygon output.",
    ),
    "dt.waterways.fused": DataTypeNode(
        type_id="dt.waterways.fused",
        theme="waterways",
        geometry_type="line",
        description="Fused waterways line output.",
    ),
    "dt.poi.fused": DataTypeNode(
        type_id="dt.poi.fused",
        theme="poi",
        geometry_type="point",
        description="Fused point-of-interest output.",
    ),
}


TASKS: Dict[str, TaskNode] = {
    "task.building.fusion": TaskNode(
        task_id="task.building.fusion",
        task_name="Building Fusion",
        category="fusion",
        description="Fuse multiple building vector sources into one output.",
        metadata=_closure_metadata(
            claim_state="runtime_supported",
            runtime_role="core_task",
            input_data_types=["dt.building.bundle", "dt.building.source_set"],
            output_data_type="dt.building.fused",
        ),
    ),
    "task.road.fusion": TaskNode(
        task_id="task.road.fusion",
        task_name="Road Fusion",
        category="fusion",
        description="Fuse multiple road vector sources into one output.",
        metadata=_closure_metadata(
            claim_state="runtime_supported",
            runtime_role="core_task",
            input_data_types=["dt.road.bundle", "dt.road.candidate"],
            output_data_type="dt.road.fused",
        ),
    ),
    "task.water.fusion": TaskNode(
        task_id="task.water.fusion",
        task_name="Water Fusion",
        category="fusion",
        description="Fuse multiple water polygon sources into one output.",
        metadata=_closure_metadata(
            claim_state="runtime_supported",
            runtime_role="core_task",
            input_data_types=["dt.water.bundle"],
            output_data_type="dt.water.fused",
        ),
    ),
    "task.waterways.fusion": TaskNode(
        task_id="task.waterways.fusion",
        task_name="Waterways Fusion",
        category="fusion",
        description="Fuse multiple waterways line sources into one output.",
        metadata=_closure_metadata(
            claim_state="runtime_supported",
            runtime_role="core_task",
            input_data_types=["dt.waterways.bundle"],
            output_data_type="dt.waterways.fused",
        ),
    ),
    "task.poi.fusion": TaskNode(
        task_id="task.poi.fusion",
        task_name="POI Fusion",
        category="fusion",
        description="Fuse multiple point-of-interest sources into one output.",
        metadata=_closure_metadata(
            claim_state="bounded_supported",
            runtime_role="core_task",
            input_data_types=["dt.poi.bundle"],
            output_data_type="dt.poi.fused",
        ),
    ),
    "task.vector.download": TaskNode(
        task_id="task.vector.download",
        task_name="Vector Data Download",
        category="acquisition",
        description="Acquire vector data required by downstream fusion or enrichment tasks.",
        metadata=_closure_metadata(
            claim_state="runtime_supported",
            runtime_role="support_task",
            output_data_type="dt.raw.vector",
        ),
    ),
    "task.trajectory_to_road": TaskNode(
        task_id="task.trajectory_to_road",
        task_name="Trajectory To Road Candidate",
        category="transform",
        description="Reserved seam for future trajectory-to-road candidate pretransform before road fusion.",
        metadata=_closure_metadata(
            claim_state="reservation_only",
            runtime_role="reserved_seam",
            input_data_types=["dt.trajectory.raw"],
            output_data_type="dt.road.candidate",
        ),
    ),
    "task.partition.aoi": TaskNode(
        task_id="task.partition.aoi",
        task_name="AOI Partition",
        category="runtime",
        description="Reserved AOI partition task for future tiled execution workflows.",
        metadata=_closure_metadata(
            claim_state="research_utility",
            runtime_role="support_task",
            input_data_types=["dt.raw.vector"],
            output_data_type="dt.partition.tile_manifest",
        ),
    ),
    "task.clip.raster.by_tile": TaskNode(
        task_id="task.clip.raster.by_tile",
        task_name="Raster Clip By Tile",
        category="runtime",
        description="Reserved tiled raster clipping task for future building enrichment workflows.",
        metadata=_closure_metadata(
            claim_state="reservation_only",
            runtime_role="reserved_seam",
            input_data_types=["dt.raster.building_presence"],
            output_data_type="dt.raster.building_presence",
        ),
    ),
    "task.merge.building.tiles.reserved": TaskNode(
        task_id="task.merge.building.tiles.reserved",
        task_name="Merge Building Tiles",
        category="runtime",
        description="Reserved seam for future tile-level building artifact stitching.",
        metadata=_closure_metadata(
            claim_state="reservation_only",
            runtime_role="reserved_seam",
            input_data_types=["dt.partition.tile_manifest"],
            output_data_type="dt.building.fused",
        ),
    ),
    "task.enrich.building.height.reserved": TaskNode(
        task_id="task.enrich.building.height.reserved",
        task_name="Enrich Building Height",
        category="enrichment",
        description="Reserved seam for future raster-backed building height enrichment.",
        metadata=_closure_metadata(
            claim_state="research_utility",
            runtime_role="support_task",
            input_data_types=["dt.raster.building_height", "dt.building.conflict_optimized"],
            output_data_type="dt.building.height_enriched",
        ),
    ),
}


SCENARIO_PROFILES: List[ScenarioProfileNode] = [
    ScenarioProfileNode(
        profile_id="scenario.flood.default",
        profile_name="Flood Default Scenario",
        disaster_types=["flood"],
        activated_tasks=["task.building.fusion", "task.road.fusion"],
        preferred_output_fields=["geometry", "confidence", "timestamp"],
        qos_priority={"accuracy": 0.35, "stability": 0.25, "freshness": 0.25, "speed": 0.15},
        qos_policy_id="qos.scenario.flood.v1",
        metadata=_closure_metadata(
            claim_state="runtime_supported",
            runtime_role="scenario_constraint",
            entry_mode="scenario_driven",
            default_task_bundle_id="task_bundle.flood.building_road",
            output_requirement_ids=["or.building.fused.v1", "or.road.fused.v1"],
        ),
    ),
    ScenarioProfileNode(
        profile_id="scenario.earthquake.default",
        profile_name="Earthquake Default Scenario",
        disaster_types=["earthquake"],
        activated_tasks=["task.building.fusion", "task.road.fusion"],
        preferred_output_fields=["geometry", "confidence", "timestamp"],
        qos_priority={"accuracy": 0.4, "stability": 0.3, "freshness": 0.15, "speed": 0.15},
        qos_policy_id="qos.scenario.earthquake.v1",
        metadata=_closure_metadata(
            claim_state="runtime_supported",
            runtime_role="scenario_constraint",
            entry_mode="scenario_driven",
            default_task_bundle_id="task_bundle.earthquake.building_road",
            output_requirement_ids=["or.building.fused.v1", "or.road.fused.v1"],
        ),
    ),
    ScenarioProfileNode(
        profile_id="scenario.typhoon.default",
        profile_name="Typhoon Default Scenario",
        disaster_types=["typhoon"],
        activated_tasks=["task.building.fusion", "task.road.fusion"],
        preferred_output_fields=["geometry", "confidence", "timestamp"],
        qos_priority={"accuracy": 0.3, "stability": 0.25, "freshness": 0.3, "speed": 0.15},
        qos_policy_id="qos.scenario.typhoon.v1",
        metadata=_closure_metadata(
            claim_state="runtime_supported",
            runtime_role="scenario_constraint",
            entry_mode="scenario_driven",
            default_task_bundle_id="task_bundle.typhoon.building_road",
            output_requirement_ids=["or.building.fused.v1", "or.road.fused.v1"],
        ),
    ),
    ScenarioProfileNode(
        profile_id="scenario.default.task",
        profile_name="Default Direct Task Profile",
        disaster_types=["generic"],
        activated_tasks=[
            "task.building.fusion",
            "task.road.fusion",
            "task.water.fusion",
            "task.waterways.fusion",
            "task.poi.fusion",
            "task.vector.download",
        ],
        preferred_output_fields=["geometry"],
        qos_priority={"accuracy": 0.35, "stability": 0.25, "freshness": 0.2, "speed": 0.2},
        qos_policy_id="qos.task.default.v1",
        metadata=_closure_metadata(
            claim_state="runtime_supported",
            runtime_role="scenario_constraint",
            entry_mode="task_driven",
            default_task_bundle_id="task_bundle.direct_request",
            output_requirement_ids=[
                "or.building.fused.v1",
                "or.road.fused.v1",
                "or.water.fused.v1",
                "or.waterways.fused.v1",
                "or.poi.fused.v1",
            ],
        ),
    ),
]


QOS_POLICIES: Dict[str, QoSPolicyNode] = {
    "qos.scenario.flood.v1": QoSPolicyNode(
        policy_id="qos.scenario.flood.v1",
        policy_name="Flood Default QoS",
        priority={"accuracy": 0.35, "stability": 0.25, "freshness": 0.25, "speed": 0.15},
        max_latency_seconds=900,
        min_success_rate=0.75,
        metadata=_closure_metadata(
            claim_state="runtime_supported",
            runtime_role="qos_policy",
            profile_scope="scenario.flood.default",
        ),
    ),
    "qos.scenario.earthquake.v1": QoSPolicyNode(
        policy_id="qos.scenario.earthquake.v1",
        policy_name="Earthquake Default QoS",
        priority={"accuracy": 0.4, "stability": 0.3, "freshness": 0.15, "speed": 0.15},
        max_latency_seconds=900,
        min_success_rate=0.78,
        metadata=_closure_metadata(
            claim_state="runtime_supported",
            runtime_role="qos_policy",
            profile_scope="scenario.earthquake.default",
        ),
    ),
    "qos.scenario.typhoon.v1": QoSPolicyNode(
        policy_id="qos.scenario.typhoon.v1",
        policy_name="Typhoon Default QoS",
        priority={"accuracy": 0.3, "stability": 0.25, "freshness": 0.3, "speed": 0.15},
        max_latency_seconds=900,
        min_success_rate=0.74,
        metadata=_closure_metadata(
            claim_state="runtime_supported",
            runtime_role="qos_policy",
            profile_scope="scenario.typhoon.default",
        ),
    ),
    "qos.task.default.v1": QoSPolicyNode(
        policy_id="qos.task.default.v1",
        policy_name="Direct Task Default QoS",
        priority={"accuracy": 0.35, "stability": 0.25, "freshness": 0.2, "speed": 0.2},
        max_latency_seconds=900,
        min_success_rate=0.72,
        metadata=_closure_metadata(
            claim_state="runtime_supported",
            runtime_role="qos_policy",
            profile_scope="scenario.default.task",
        ),
    ),
}


ALGORITHMS: Dict[str, AlgorithmNode] = {
    "algo.fusion.building.v1": AlgorithmNode(
        algo_id="algo.fusion.building.v1",
        algo_name="Building Fusion Legacy",
        input_types=["dt.building.bundle"],
        output_type="dt.building.fused",
        task_type="building_fusion",
        tool_ref="adapters.building_adapter:run_building_fusion",
        success_rate=0.92,
        accuracy_score=0.89,
        stability_score=0.74,
        usage_mode="throughput",
        metadata={
            "selection_profile": "primary",
            "evidence_basis": "legacy_default_runtime",
            "runtime_status": "runtime_candidate",
            "selectable_now": True,
            "claim_state": "runtime_supported",
        },
        alternatives=["algo.fusion.building.safe"],
    ),
    "algo.fusion.building.safe": AlgorithmNode(
        algo_id="algo.fusion.building.safe",
        algo_name="Building Fusion Safe Fallback",
        input_types=["dt.building.bundle"],
        output_type="dt.building.fused",
        task_type="building_fusion",
        tool_ref="adapters.building_adapter:run_building_fusion",
        success_rate=0.75,
        accuracy_score=0.79,
        stability_score=0.91,
        usage_mode="conservative",
        metadata={
            "selection_profile": "fallback",
            "evidence_basis": "conservative_thresholds",
            "runtime_status": "runtime_candidate",
            "selectable_now": True,
            "claim_state": "runtime_supported",
        },
        alternatives=["algo.fusion.building.v1"],
    ),
    "algo.fusion.road.v1": AlgorithmNode(
        algo_id="algo.fusion.road.v1",
        algo_name="Road Fusion Legacy (Deprecated)",
        input_types=["dt.road.bundle"],
        output_type="dt.road.fused",
        task_type="road_fusion",
        tool_ref="adapters.road_adapter:run_road_fusion",
        success_rate=0.9,
        accuracy_score=0.86,
        stability_score=0.72,
        usage_mode="deprecated",
        metadata={
            "selection_profile": "deprecated",
            "evidence_basis": "superseded_by_v7_conflation",
            "runtime_status": "deprecated",
            "selectable_now": False,
            "claim_state": "deprecated",
            "deprecated_by": "algo.fusion.road.conflation.v7",
        },
        alternatives=[],
    ),
    "algo.fusion.road.safe": AlgorithmNode(
        algo_id="algo.fusion.road.safe",
        algo_name="Road Fusion Safe Fallback (Deprecated)",
        input_types=["dt.road.bundle"],
        output_type="dt.road.fused",
        task_type="road_fusion",
        tool_ref="adapters.road_adapter:run_road_fusion",
        success_rate=0.72,
        accuracy_score=0.77,
        stability_score=0.9,
        usage_mode="deprecated",
        metadata={
            "selection_profile": "deprecated",
            "evidence_basis": "superseded_by_v7_profile_conservative",
            "runtime_status": "deprecated",
            "selectable_now": False,
            "claim_state": "deprecated",
            "deprecated_by": "algo.fusion.road.conflation.v7",
        },
        alternatives=[],
    ),
    "algo.fusion.water.v1": AlgorithmNode(
        algo_id="algo.fusion.water.v1",
        algo_name="Water Polygon Fusion (Deprecated)",
        input_types=["dt.water.bundle"],
        output_type="dt.water.fused",
        task_type="water_fusion",
        tool_ref="adapters.water_adapter:run_water_fusion",
        success_rate=0.84,
        accuracy_score=0.82,
        stability_score=0.88,
        usage_mode="deprecated",
        metadata={
            "selection_profile": "deprecated",
            "evidence_basis": "superseded_by_polygon_priority_merge_v2",
            "runtime_scope": "uploaded_or_task_driven_auto",
            "runtime_status": "deprecated",
            "selectable_now": False,
            "claim_state": "deprecated",
            "deprecated_by": "algo.fusion.water_polygon.priority_merge.v2",
        },
    ),
    "algo.fusion.poi.v1": AlgorithmNode(
        algo_id="algo.fusion.poi.v1",
        algo_name="POI Fusion",
        input_types=["dt.poi.bundle"],
        output_type="dt.poi.fused",
        task_type="poi_fusion",
        tool_ref="adapters.poi_adapter:run_poi_fusion",
        success_rate=0.8,
        accuracy_score=0.78,
        stability_score=0.86,
        usage_mode="conservative",
        metadata={
            "selection_profile": "primary",
            "evidence_basis": "shared_bundle_runtime",
            "runtime_scope": "uploaded_or_task_driven_auto",
            "runtime_status": "runtime_candidate",
            "selectable_now": True,
            "claim_state": "bounded_supported",
        },
    ),
    "algo.partition.aoi.grid.v1": AlgorithmNode(
        algo_id="algo.partition.aoi.grid.v1",
        algo_name="AOI Grid Partition Reserved",
        input_types=["dt.raw.vector"],
        output_type="dt.partition.tile_manifest",
        task_type="runtime_partition",
        tool_ref="reserved:aoi_grid_partition",
        success_rate=0.0,
        usage_mode="reserved",
        metadata={
            "runtime_status": "reservation_only",
            "selectable_now": False,
            "claim_state": "reservation_only",
        },
    ),
    "algo.clip.raster.tile.v1": AlgorithmNode(
        algo_id="algo.clip.raster.tile.v1",
        algo_name="Raster Tile Clip Reserved",
        input_types=["dt.raster.building_presence"],
        output_type="dt.raster.building_presence",
        task_type="raster_clip",
        tool_ref="reserved:raster_tile_clip",
        success_rate=0.0,
        usage_mode="reserved",
        metadata={
            "runtime_status": "reservation_only",
            "selectable_now": False,
            "claim_state": "reservation_only",
        },
    ),
    "algo.fusion.building.multi_source.reserved": AlgorithmNode(
        algo_id="algo.fusion.building.multi_source.reserved",
        algo_name="Multi-Source Building Fusion Reserved",
        input_types=["dt.building.source_set"],
        output_type="dt.building.fused",
        task_type="building_fusion",
        tool_ref="reserved:multi_source_building_fusion",
        success_rate=0.0,
        usage_mode="reserved",
        metadata={
            "runtime_status": "reservation_only",
            "selectable_now": False,
            "claim_state": "reservation_only",
        },
    ),
    "algo.merge.building.tiles.reserved": AlgorithmNode(
        algo_id="algo.merge.building.tiles.reserved",
        algo_name="Building Tile Merge Reserved",
        input_types=["dt.partition.tile_manifest"],
        output_type="dt.building.fused",
        task_type="runtime_merge",
        tool_ref="reserved:building_tile_merge",
        success_rate=0.0,
        usage_mode="reserved",
        metadata={
            "runtime_status": "reservation_only",
            "selectable_now": False,
            "claim_state": "reservation_only",
        },
    ),
    "algo.enrich.building.height_from_raster.reserved": AlgorithmNode(
        algo_id="algo.enrich.building.height_from_raster.reserved",
        algo_name="Building Height Enrichment From Raster Reserved",
        input_types=["dt.raster.building_presence"],
        output_type="dt.building.fused",
        task_type="enrichment",
        tool_ref="reserved:building_height_from_raster",
        success_rate=0.0,
        usage_mode="reserved",
        metadata={
            "runtime_status": "reservation_only",
            "selectable_now": False,
            "claim_state": "reservation_only",
        },
    ),
    "algo.transform.raw_to_building_bundle": AlgorithmNode(
        algo_id="algo.transform.raw_to_building_bundle",
        algo_name="Raw Vector to Building Bundle",
        input_types=["dt.raw.vector"],
        output_type="dt.building.bundle",
        task_type="transform",
        tool_ref="builtin:transform",
        success_rate=0.98,
        accuracy_score=0.97,
        stability_score=0.96,
        usage_mode="normalization",
        metadata={
            "selection_profile": "preparation",
            "evidence_basis": "deterministic_transform",
        },
    ),
    "algo.transform.raw_to_road_bundle": AlgorithmNode(
        algo_id="algo.transform.raw_to_road_bundle",
        algo_name="Raw Vector to Road Bundle",
        input_types=["dt.raw.vector"],
        output_type="dt.road.bundle",
        task_type="transform",
        tool_ref="builtin:transform",
        success_rate=0.98,
        accuracy_score=0.97,
        stability_score=0.96,
        usage_mode="normalization",
        metadata={
            "selection_profile": "preparation",
            "evidence_basis": "deterministic_transform",
        },
    ),
    "algo.transform.trajectory_to_road_candidate": AlgorithmNode(
        algo_id="algo.transform.trajectory_to_road_candidate",
        algo_name="Trajectory To Road Candidate Reserved Seam",
        input_types=["dt.trajectory.raw"],
        output_type="dt.road.candidate",
        task_type="transform",
        tool_ref="builtin:trajectory_pretransform_reserved",
        success_rate=0.0,
        accuracy_score=0.0,
        stability_score=1.0,
        usage_mode="reserved",
        metadata={
            "selection_profile": "reserved_seam",
            "evidence_basis": "phase4_transform_reservation",
            "runtime_scope": "metadata_only",
            "activation": "non_default",
            "runtime_status": "reservation_only",
            "selectable_now": False,
            "claim_state": "reservation_only",
        },
    ),
}

PARAMETER_SPECS: Dict[str, List[AlgorithmParameterSpec]] = {
    # Building fusion parameters are derived from legacy adapter semantics:
    # - match similarity threshold: label=1 when similarity > threshold
    # - one-to-one thresholds: sim_area/sim_shape/sim_overlap must each be >= threshold
    "algo.fusion.building.v1": [
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.building.v1.match_similarity_threshold",
            algo_id="algo.fusion.building.v1",
            key="match_similarity_threshold",
            label="Match Similarity Threshold",
            param_type="float",
            default=0.3,
            min_value=0.0,
            max_value=1.0,
            unit="ratio",
            description="Pairs with similarity > this value are treated as matched (legacy label=1).",
            required=False,
            tunable=True,
            optimization_tags=["precision", "recall", "matching"],
            conditional_defaults=[
                {
                    "when": {"source_combination": ["raw.google.building", "raw.osm.building"]},
                    "value": 0.75,
                    "provenance": {
                        "source": "manual_seed",
                        "reason": "Google/OSM building matches need stricter geometry confidence.",
                    },
                },
                {
                    "when": {"source_combination": ["raw.microsoft.building", "raw.osm.building"]},
                    "value": 0.70,
                    "provenance": {"source": "static_seed", "reason": "Current Microsoft/OSM default."},
                },
                {
                    "when": {"region_country_name": "Nepal"},
                    "value": 0.65,
                    "provenance": {"source": "operator_annotation", "reason": "Nepal training run tolerance."},
                },
                {
                    "when": {"region_country_name": "Mongolia"},
                    "value": 0.75,
                    "provenance": {
                        "source": "operator_annotation",
                        "reason": "Mongolia training run precision preference.",
                    },
                },
            ],
            default_provenance={"source": "static_seed", "reason": "Original KG seed default."},
            order=10,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.building.v1.one_to_one_min_area_similarity",
            algo_id="algo.fusion.building.v1",
            key="one_to_one_min_area_similarity",
            label="One-to-One Min Area Similarity",
            param_type="float",
            default=0.3,
            min_value=0.0,
            max_value=1.0,
            unit="ratio",
            description="For 1:1 matches, sim_area must be >= this value to fuse as one-to-one.",
            required=False,
            tunable=True,
            optimization_tags=["precision", "stability", "shape_consistency"],
            default_provenance={"source": "static_seed"},
            order=20,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.building.v1.one_to_one_min_shape_similarity",
            algo_id="algo.fusion.building.v1",
            key="one_to_one_min_shape_similarity",
            label="One-to-One Min Shape Similarity",
            param_type="float",
            default=0.3,
            min_value=0.0,
            max_value=1.0,
            unit="ratio",
            description="For 1:1 matches, sim_shape must be >= this value to fuse as one-to-one.",
            required=False,
            tunable=True,
            optimization_tags=["precision", "stability", "shape_consistency"],
            default_provenance={"source": "static_seed"},
            order=30,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.building.v1.one_to_one_min_overlap_similarity",
            algo_id="algo.fusion.building.v1",
            key="one_to_one_min_overlap_similarity",
            label="One-to-One Min Overlap Similarity",
            param_type="float",
            default=0.3,
            min_value=0.0,
            max_value=1.0,
            unit="ratio",
            description="For 1:1 matches, sim_overlap must be >= this value to fuse as one-to-one.",
            required=False,
            tunable=True,
            optimization_tags=["precision", "recall", "overlap_consistency"],
            default_provenance={"source": "static_seed"},
            order=40,
        ),
    ],
    "algo.fusion.building.safe": [
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.building.safe.match_similarity_threshold",
            algo_id="algo.fusion.building.safe",
            key="match_similarity_threshold",
            label="Match Similarity Threshold",
            param_type="float",
            default=0.4,
            min_value=0.0,
            max_value=1.0,
            unit="ratio",
            description="Conservative match threshold for safe mode.",
            required=False,
            tunable=True,
            optimization_tags=["precision", "stability", "matching"],
            default_provenance={"source": "static_seed"},
            order=10,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.building.safe.one_to_one_min_area_similarity",
            algo_id="algo.fusion.building.safe",
            key="one_to_one_min_area_similarity",
            label="One-to-One Min Area Similarity",
            param_type="float",
            default=0.45,
            min_value=0.0,
            max_value=1.0,
            unit="ratio",
            description="Conservative area similarity threshold for safe mode.",
            required=False,
            tunable=True,
            optimization_tags=["precision", "stability", "shape_consistency"],
            default_provenance={"source": "static_seed"},
            order=20,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.building.safe.one_to_one_min_shape_similarity",
            algo_id="algo.fusion.building.safe",
            key="one_to_one_min_shape_similarity",
            label="One-to-One Min Shape Similarity",
            param_type="float",
            default=0.45,
            min_value=0.0,
            max_value=1.0,
            unit="ratio",
            description="Conservative shape similarity threshold for safe mode.",
            required=False,
            tunable=True,
            optimization_tags=["precision", "stability", "shape_consistency"],
            default_provenance={"source": "static_seed"},
            order=30,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.building.safe.one_to_one_min_overlap_similarity",
            algo_id="algo.fusion.building.safe",
            key="one_to_one_min_overlap_similarity",
            label="One-to-One Min Overlap Similarity",
            param_type="float",
            default=0.4,
            min_value=0.0,
            max_value=1.0,
            unit="ratio",
            description="Conservative one-to-one overlap threshold for safe mode.",
            required=False,
            tunable=True,
            optimization_tags=["precision", "stability", "overlap_consistency"],
            default_provenance={"source": "static_seed"},
            order=40,
        ),
    ],
    # Road fusion parameters are derived from legacy algorithm constants and adapter defaults:
    # - ANGLE_THRESHOLD / SNAP_TOLERANCE / BUFFER_DIST / MAX_HAUSDORFF in Algorithm/line.py
    # - dedupe buffer_distance default in adapters/road_adapter.py
    "algo.fusion.road.v1": [
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.road.v1.angle_threshold_deg",
            algo_id="algo.fusion.road.v1",
            key="angle_threshold_deg",
            label="Split Angle Threshold",
            param_type="int",
            default=135,
            min_value=0.0,
            max_value=180.0,
            unit="deg",
            description="Split lines at sharp turns: angles below this threshold trigger a split.",
            required=False,
            tunable=True,
            optimization_tags=["stability", "segmentation"],
            order=10,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.road.v1.snap_tolerance_m",
            algo_id="algo.fusion.road.v1",
            key="snap_tolerance_m",
            label="Snap Tolerance",
            param_type="float",
            default=1.0,
            min_value=0.0,
            max_value=10.0,
            unit="m",
            description="Endpoint snap tolerance used when normalizing line endpoints.",
            required=False,
            tunable=True,
            optimization_tags=["stability", "topology"],
            order=20,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.road.v1.match_buffer_m",
            algo_id="algo.fusion.road.v1",
            key="match_buffer_m",
            label="Match Buffer Distance",
            param_type="float",
            default=20.0,
            min_value=0.0,
            max_value=100.0,
            unit="m",
            description="Buffer radius for candidate matching between OSM and reference lines.",
            required=False,
            tunable=True,
            optimization_tags=["recall", "matching"],
            order=30,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.road.v1.max_hausdorff_m",
            algo_id="algo.fusion.road.v1",
            key="max_hausdorff_m",
            label="Max Hausdorff Distance",
            param_type="float",
            default=15.0,
            min_value=0.0,
            max_value=100.0,
            unit="m",
            description="Maximum Hausdorff distance allowed to consider two lines as a match.",
            required=False,
            tunable=True,
            optimization_tags=["precision", "stability", "matching"],
            order=40,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.road.v1.dedupe_buffer_m",
            algo_id="algo.fusion.road.v1",
            key="dedupe_buffer_m",
            label="Dedupe Buffer Distance",
            param_type="float",
            default=15.0,
            min_value=0.0,
            max_value=100.0,
            unit="m",
            description="Buffer distance used during post-fusion deduplication.",
            required=False,
            tunable=True,
            optimization_tags=["stability", "deduplication"],
            order=50,
        ),
    ],
    "algo.fusion.road.safe": [
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.road.safe.angle_threshold_deg",
            algo_id="algo.fusion.road.safe",
            key="angle_threshold_deg",
            label="Split Angle Threshold",
            param_type="int",
            default=120,
            min_value=0.0,
            max_value=180.0,
            unit="deg",
            description="Conservative split angle threshold for safe mode.",
            required=False,
            tunable=True,
            optimization_tags=["stability", "segmentation"],
            order=10,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.road.safe.snap_tolerance_m",
            algo_id="algo.fusion.road.safe",
            key="snap_tolerance_m",
            label="Snap Tolerance",
            param_type="float",
            default=0.75,
            min_value=0.0,
            max_value=10.0,
            unit="m",
            description="Conservative endpoint snap tolerance for safe mode.",
            required=False,
            tunable=True,
            optimization_tags=["stability", "topology"],
            order=20,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.road.safe.match_buffer_m",
            algo_id="algo.fusion.road.safe",
            key="match_buffer_m",
            label="Match Buffer Distance",
            param_type="float",
            default=15.0,
            min_value=0.0,
            max_value=100.0,
            unit="m",
            description="Conservative match buffer for safe mode.",
            required=False,
            tunable=True,
            optimization_tags=["precision", "matching"],
            order=30,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.road.safe.max_hausdorff_m",
            algo_id="algo.fusion.road.safe",
            key="max_hausdorff_m",
            label="Max Hausdorff Distance",
            param_type="float",
            default=10.0,
            min_value=0.0,
            max_value=100.0,
            unit="m",
            description="Conservative Hausdorff threshold for safe mode.",
            required=False,
            tunable=True,
            optimization_tags=["precision", "stability", "matching"],
            order=40,
        ),
        AlgorithmParameterSpec(
            spec_id="ps.algo.fusion.road.safe.dedupe_buffer_m",
            algo_id="algo.fusion.road.safe",
            key="dedupe_buffer_m",
            label="Dedupe Buffer Distance",
            param_type="float",
            default=12.0,
            min_value=0.0,
            max_value=100.0,
            unit="m",
            description="Conservative dedupe buffer for safe mode.",
            required=False,
            tunable=True,
            optimization_tags=["stability", "deduplication"],
            order=50,
        ),
    ],
}


WORKFLOW_PATTERNS: List[WorkflowPatternNode] = [
    WorkflowPatternNode(
        pattern_id="wp.flood.building.default",
        pattern_name="Flood Building Fusion",
        job_type=JobType.building,
        disaster_types=["flood", "typhoon", "generic"],
        success_rate=0.88,
        metadata={
            "version": "1.0.0",
            "runtime_status": "runtime_candidate",
            "scenario_focus": "flood",
            "strategy": "throughput",
        },
        steps=[
            PatternStep(
                order=1,
                name="building_fusion",
                algorithm_id="algo.fusion.building.v1",
                input_data_type="dt.building.bundle",
                output_data_type="dt.building.fused",
                data_source_id="upload.bundle",
            )
        ],
    ),
    WorkflowPatternNode(
        pattern_id="wp.flood.building.safe",
        pattern_name="Flood Building Fusion Safe Route",
        job_type=JobType.building,
        disaster_types=["flood", "generic"],
        success_rate=0.82,
        metadata={
            "version": "1.0.0",
            "runtime_status": "runtime_candidate",
            "scenario_focus": "flood",
            "mode": "safe",
            "strategy": "conservative",
        },
        steps=[
            PatternStep(
                order=1,
                name="building_fusion_safe",
                algorithm_id="algo.fusion.building.safe",
                input_data_type="dt.building.bundle",
                output_data_type="dt.building.fused",
                data_source_id="upload.bundle",
            )
        ],
    ),
    WorkflowPatternNode(
        pattern_id="wp.earthquake.building.default",
        pattern_name="Earthquake Building Fusion",
        job_type=JobType.building,
        disaster_types=["earthquake"],
        success_rate=0.91,
        metadata={
            "version": "1.0.0",
            "runtime_status": "runtime_candidate",
            "scenario_focus": "earthquake",
            "strategy": "throughput",
        },
        steps=[
            PatternStep(
                order=1,
                name="building_fusion_earthquake",
                algorithm_id="algo.fusion.building.v1",
                input_data_type="dt.building.bundle",
                output_data_type="dt.building.fused",
                data_source_id="upload.bundle",
            )
        ],
    ),
    WorkflowPatternNode(
        pattern_id="wp.earthquake.building.safe",
        pattern_name="Earthquake Building Fusion Safe Route",
        job_type=JobType.building,
        disaster_types=["earthquake"],
        success_rate=0.85,
        metadata={
            "version": "1.0.0",
            "runtime_status": "runtime_candidate",
            "scenario_focus": "earthquake",
            "mode": "safe",
            "strategy": "conservative",
        },
        steps=[
            PatternStep(
                order=1,
                name="building_fusion_safe",
                algorithm_id="algo.fusion.building.safe",
                input_data_type="dt.building.bundle",
                output_data_type="dt.building.fused",
                data_source_id="upload.bundle",
            )
        ],
    ),
    WorkflowPatternNode(
        pattern_id="wp.flood.road.default",
        pattern_name="Flood Road Conflation V7",
        job_type=JobType.road,
        disaster_types=["flood", "earthquake", "generic"],
        success_rate=0.86,
        metadata={
            "version": "7.0.0",
            "runtime_status": "runtime_candidate",
            "scenario_focus": "flood",
            "strategy": "balanced",
            "input_strategy": "task_driven_auto_supported",
            "source_family": "catalog_road_bundle",
        },
        steps=[
            PatternStep(
                order=1,
                name="road_conflation_v7",
                algorithm_id="algo.fusion.road.conflation.v7",
                input_data_type="dt.road.bundle",
                output_data_type="dt.road.fused",
                data_source_id="catalog.flood.road",
            )
        ],
    ),
    WorkflowPatternNode(
        pattern_id="wp.flood.water.default",
        pattern_name="Flood Water Polygon Fusion",
        job_type=JobType.water,
        disaster_types=["flood", "generic"],
        success_rate=0.84,
        metadata={
            "version": "1.0.0",
            "runtime_status": "runtime_candidate",
            "scenario_focus": "flood",
            "strategy": "conservative",
            "input_strategy": "task_driven_auto_supported",
            "source_family": "catalog_water_bundle",
            "water_semantics": "polygon",
        },
        steps=[
            PatternStep(
                order=1,
                name="water_polygon_priority_merge",
                algorithm_id="algo.fusion.water_polygon.priority_merge.v2",
                input_data_type="dt.water.bundle",
                output_data_type="dt.water.fused",
                data_source_id="catalog.flood.water",
            )
        ],
    ),
    WorkflowPatternNode(
        pattern_id="wp.flood.water_polygon.default",
        pattern_name="Flood Water Polygon Priority Merge",
        job_type=JobType.water,
        disaster_types=["flood", "generic"],
        success_rate=0.79,
        metadata={
            "version": "2.0.0",
            "runtime_status": "runtime_candidate",
            "scenario_focus": "flood",
            "strategy": "conservative",
            "input_strategy": "task_driven_auto_supported",
            "source_family": "catalog_water_bundle",
            "water_semantics": "polygon",
        },
        steps=[
            PatternStep(
                order=1,
                name="water_polygon_priority_merge",
                algorithm_id="algo.fusion.water_polygon.priority_merge.v2",
                input_data_type="dt.water.bundle",
                output_data_type="dt.water.fused",
                data_source_id="catalog.flood.water_polygon",
            )
        ],
    ),
    WorkflowPatternNode(
        pattern_id="wp.flood.waterways.default",
        pattern_name="Flood Waterways Conflation V7",
        job_type=JobType.water,
        disaster_types=["flood", "generic"],
        success_rate=0.8,
        metadata={
            "version": "7.0.0",
            "runtime_status": "runtime_candidate",
            "scenario_focus": "flood",
            "strategy": "balanced",
            "input_strategy": "task_driven_auto_supported",
            "source_family": "catalog_waterways_bundle",
            "water_semantics": "waterways_line",
        },
        steps=[
            PatternStep(
                order=1,
                name="waterways_conflation_v7",
                algorithm_id="algo.fusion.waterways.conflation.v7",
                input_data_type="dt.waterways.bundle",
                output_data_type="dt.waterways.fused",
                data_source_id="catalog.flood.waterways",
            )
        ],
    ),
    WorkflowPatternNode(
        pattern_id="wp.generic.poi.default",
        pattern_name="Generic POI Fusion",
        job_type=JobType.poi,
        disaster_types=["generic"],
        success_rate=0.8,
        metadata={
            "version": "1.0.0",
            "runtime_status": "runtime_candidate",
            "scenario_focus": "generic",
            "strategy": "conservative",
            "input_strategy": "task_driven_auto_supported",
            "source_family": "catalog_poi_bundle",
        },
        steps=[
            PatternStep(
                order=1,
                name="poi_fusion",
                algorithm_id="algo.fusion.poi.v1",
                input_data_type="dt.poi.bundle",
                output_data_type="dt.poi.fused",
                data_source_id="catalog.generic.poi",
            )
        ],
    ),
    WorkflowPatternNode(
        pattern_id="wp.typhoon.road.default",
        pattern_name="Typhoon Road Conflation V7",
        job_type=JobType.road,
        disaster_types=["typhoon"],
        success_rate=0.9,
        metadata={
            "version": "7.0.0",
            "runtime_status": "runtime_candidate",
            "scenario_focus": "typhoon",
            "strategy": "balanced",
            "input_strategy": "task_driven_auto_supported",
            "source_family": "catalog_road_bundle",
        },
        steps=[
            PatternStep(
                order=1,
                name="road_conflation_v7_typhoon",
                algorithm_id="algo.fusion.road.conflation.v7",
                input_data_type="dt.road.bundle",
                output_data_type="dt.road.fused",
                data_source_id="catalog.typhoon.road",
            )
        ],
    ),
]


DATA_SOURCES: List[DataSourceNode] = build_data_sources()


OUTPUT_SCHEMA_POLICIES: Dict[str, OutputSchemaPolicy] = {
    "dt.building.fused": OutputSchemaPolicy(
        policy_id="osp.building.fused.v1",
        output_type="dt.building.fused",
        job_type=JobType.building,
        retention_mode="preserve_listed",
        required_fields=["geometry"],
        optional_fields=[
            "osm_id",
            "fclass",
            "name",
            "type",
            "longitude",
            "latitude",
            "area_in_me",
            "confidence",
        ],
        rename_hints={
            "geometry_x": "geometry",
            "geometry_y": "geometry",
        },
        compatibility_basis="field_names",
        metadata=_closure_metadata(
            claim_state="runtime_supported",
            runtime_role="output_schema_policy",
            policy_scope="current_runtime",
            notes="Expose stable fused building columns without changing adapter behavior.",
        ),
    ),
    "dt.road.fused": OutputSchemaPolicy(
        policy_id="osp.road.fused.v1",
        output_type="dt.road.fused",
        job_type=JobType.road,
        retention_mode="preserve_listed",
        required_fields=["geometry"],
        optional_fields=[
            "fusion_source",
            "match_role",
            "matched_supplement_segment_id",
            "supplement_segment_id",
            "road_class",
            "source_layer",
            "residual_from_matched",
            "residual_part",
            "osm_id",
            "FID_1",
            "fclass",
            "name",
            "osm_name",
            "road_name",
            "source_feature_id",
            "surface",
            "lanes",
            "ref",
        ],
        rename_hints={},
        compatibility_basis="field_names",
        metadata=_closure_metadata(
            claim_state="runtime_supported",
            runtime_role="output_schema_policy",
            policy_scope="current_runtime",
            quality_contract_id="contract.road.fused.v1",
            notes="Road output schema documents the canonical V7 conflation fields exposed by the active runtime path.",
        ),
    ),
    "dt.water.fused": OutputSchemaPolicy(
        policy_id="osp.water.fused.v1",
        output_type="dt.water.fused",
        job_type=JobType.water,
        retention_mode="preserve_listed",
        required_fields=["geometry"],
        optional_fields=[
            "OSM_ID",
            "REF_ID",
            "MATCH_REF",
            "OV_RATIO",
            "MATCH_CNT",
            "SRC",
            "NAME",
            "FCLASS",
            "WATER_TY",
        ],
        rename_hints={},
        compatibility_basis="field_names",
        metadata=_closure_metadata(
            claim_state="runtime_supported",
            runtime_role="output_schema_policy",
            policy_scope="current_runtime",
            enforcement="metadata_only",
            notes=(
                "Water output schema documents current shared bundle runtime columns "
                "for uploaded and task-driven auto runs without enforcing adapter output."
            ),
        ),
    ),
    "dt.waterways.fused": OutputSchemaPolicy(
        policy_id="osp.waterways.fused.v1",
        output_type="dt.waterways.fused",
        job_type=JobType.water,
        retention_mode="preserve_listed",
        required_fields=["geometry", "fusion_source", "match_role", "waterway_class", "source_layer"],
        optional_fields=[
            "matched_supplement_high",
            "matched_supplement_loose",
            "supplement_segment_id",
            "matched_base_segment_id",
            "name",
            "name_en",
            "name_ur",
            "width",
            "depth",
            "covered",
            "layer",
            "blockage",
            "tunnel",
            "natural",
            "water",
            "supplement_source",
            "residual_from_matched",
            "residual_part",
            "residual_parent_FID_1",
        ],
        rename_hints={},
        compatibility_basis="field_names",
        metadata=_closure_metadata(
            claim_state="runtime_supported",
            runtime_role="output_schema_policy",
            policy_scope="current_runtime",
            enforcement="metadata_only",
            water_semantics="waterways_line",
            notes="Waterways output schema documents the canonical V7 line conflation fields and keeps line semantics explicit.",
        ),
    ),
    "dt.poi.fused": OutputSchemaPolicy(
        policy_id="osp.poi.fused.v1",
        output_type="dt.poi.fused",
        job_type=JobType.poi,
        retention_mode="preserve_listed",
        required_fields=["geometry"],
        optional_fields=[
            "POI_ID",
            "OSM_ID",
            "REF_ID",
            "MATCH_REF",
            "DIST_M",
            "SRC",
            "NAME",
            "CATEGORY",
        ],
        rename_hints={},
        compatibility_basis="field_names",
        metadata=_closure_metadata(
            claim_state="bounded_supported",
            runtime_role="output_schema_policy",
            policy_scope="current_runtime",
            enforcement="metadata_only",
            notes=(
                "POI output schema documents current shared bundle runtime columns "
                "for uploaded and task-driven auto runs without enforcing adapter output."
            ),
        ),
    ),
}


OUTPUT_REQUIREMENTS: Dict[str, OutputRequirementNode] = {
    "or.building.fused.v1": OutputRequirementNode(
        requirement_id="or.building.fused.v1",
        job_type=JobType.building,
        output_type="dt.building.fused",
        schema_policy_id="osp.building.fused.v1",
        required_fields=["geometry"],
        preferred_fields=["confidence", "timestamp"],
        optional_fields=["osm_id", "name", "type", "longitude", "latitude", "area_in_me"],
        metadata=_closure_metadata(
            claim_state="runtime_supported",
            runtime_role="output_requirement",
            output_requirement_scope="shared_runtime",
        ),
    ),
    "or.road.fused.v1": OutputRequirementNode(
        requirement_id="or.road.fused.v1",
        job_type=JobType.road,
        output_type="dt.road.fused",
        schema_policy_id="osp.road.fused.v1",
        required_fields=["geometry"],
        preferred_fields=["confidence", "timestamp"],
        optional_fields=[
            "fusion_source",
            "match_role",
            "matched_supplement_segment_id",
            "supplement_segment_id",
            "road_class",
            "source_layer",
            "residual_from_matched",
            "residual_part",
            "osm_id",
            "FID_1",
            "fclass",
        ],
        metadata=_closure_metadata(
            claim_state="runtime_supported",
            runtime_role="output_requirement",
            output_requirement_scope="shared_runtime",
        ),
    ),
    "or.water.fused.v1": OutputRequirementNode(
        requirement_id="or.water.fused.v1",
        job_type=JobType.water,
        output_type="dt.water.fused",
        schema_policy_id="osp.water.fused.v1",
        required_fields=["geometry"],
        preferred_fields=["timestamp"],
        optional_fields=["OSM_ID", "REF_ID", "MATCH_REF", "OV_RATIO", "MATCH_CNT", "SRC", "NAME", "FCLASS", "WATER_TY"],
        metadata=_closure_metadata(
            claim_state="runtime_supported",
            runtime_role="output_requirement",
            output_requirement_scope="shared_runtime",
        ),
    ),
    "or.waterways.fused.v1": OutputRequirementNode(
        requirement_id="or.waterways.fused.v1",
        job_type=JobType.water,
        output_type="dt.waterways.fused",
        schema_policy_id="osp.waterways.fused.v1",
        required_fields=["geometry", "fusion_source", "match_role", "waterway_class", "source_layer"],
        preferred_fields=["timestamp", "name", "name_en"],
        optional_fields=[
            "matched_supplement_high",
            "matched_supplement_loose",
            "supplement_segment_id",
            "matched_base_segment_id",
            "supplement_source",
            "residual_from_matched",
            "residual_part",
            "residual_parent_FID_1",
        ],
        metadata=_closure_metadata(
            claim_state="runtime_supported",
            runtime_role="output_requirement",
            output_requirement_scope="shared_runtime",
            water_semantics="waterways_line",
        ),
    ),
    "or.poi.fused.v1": OutputRequirementNode(
        requirement_id="or.poi.fused.v1",
        job_type=JobType.poi,
        output_type="dt.poi.fused",
        schema_policy_id="osp.poi.fused.v1",
        required_fields=["geometry"],
        preferred_fields=["timestamp"],
        optional_fields=["POI_ID", "OSM_ID", "REF_ID", "MATCH_REF", "DIST_M", "SRC", "NAME", "CATEGORY"],
        metadata=_closure_metadata(
            claim_state="bounded_supported",
            runtime_role="output_requirement",
            output_requirement_scope="shared_runtime",
        ),
    ),
}


DATA_NEEDS: List[DataNeedNode] = [
    DataNeedNode(
        need_id="dn.task.building.fusion.input",
        task_id="task.building.fusion",
        data_type_id="dt.building.bundle",
        direction="consumes",
        required=True,
        description="Building fusion consumes prepared building bundles in the shared runtime path.",
        metadata=_closure_metadata(claim_state="runtime_supported", runtime_role="data_need"),
    ),
    DataNeedNode(
        need_id="dn.task.building.fusion.output",
        task_id="task.building.fusion",
        data_type_id="dt.building.fused",
        direction="produces",
        required=True,
        description="Building fusion produces fused building output.",
        metadata=_closure_metadata(claim_state="runtime_supported", runtime_role="data_need"),
    ),
    DataNeedNode(
        need_id="dn.task.road.fusion.input",
        task_id="task.road.fusion",
        data_type_id="dt.road.bundle",
        direction="consumes",
        required=True,
        description="Road fusion consumes prepared road bundles.",
        metadata=_closure_metadata(claim_state="runtime_supported", runtime_role="data_need"),
    ),
    DataNeedNode(
        need_id="dn.task.road.fusion.output",
        task_id="task.road.fusion",
        data_type_id="dt.road.fused",
        direction="produces",
        required=True,
        description="Road fusion produces fused road output.",
        metadata=_closure_metadata(claim_state="runtime_supported", runtime_role="data_need"),
    ),
    DataNeedNode(
        need_id="dn.task.water.fusion.input",
        task_id="task.water.fusion",
        data_type_id="dt.water.bundle",
        direction="consumes",
        required=True,
        description="Water fusion consumes prepared water bundles.",
        metadata=_closure_metadata(claim_state="runtime_supported", runtime_role="data_need"),
    ),
    DataNeedNode(
        need_id="dn.task.water.fusion.output",
        task_id="task.water.fusion",
        data_type_id="dt.water.fused",
        direction="produces",
        required=True,
        description="Water fusion produces fused water polygons.",
        metadata=_closure_metadata(claim_state="runtime_supported", runtime_role="data_need"),
    ),
    DataNeedNode(
        need_id="dn.task.waterways.fusion.input",
        task_id="task.waterways.fusion",
        data_type_id="dt.waterways.bundle",
        direction="consumes",
        required=True,
        description="Waterways fusion consumes prepared waterways bundles.",
        metadata=_closure_metadata(claim_state="runtime_supported", runtime_role="data_need"),
    ),
    DataNeedNode(
        need_id="dn.task.waterways.fusion.output",
        task_id="task.waterways.fusion",
        data_type_id="dt.waterways.fused",
        direction="produces",
        required=True,
        description="Waterways fusion produces fused waterways output.",
        metadata=_closure_metadata(claim_state="runtime_supported", runtime_role="data_need"),
    ),
    DataNeedNode(
        need_id="dn.task.poi.fusion.input",
        task_id="task.poi.fusion",
        data_type_id="dt.poi.bundle",
        direction="consumes",
        required=True,
        description="POI fusion consumes prepared POI bundles.",
        metadata=_closure_metadata(claim_state="bounded_supported", runtime_role="data_need"),
    ),
    DataNeedNode(
        need_id="dn.task.poi.fusion.output",
        task_id="task.poi.fusion",
        data_type_id="dt.poi.fused",
        direction="produces",
        required=True,
        description="POI fusion produces fused POI output.",
        metadata=_closure_metadata(claim_state="bounded_supported", runtime_role="data_need"),
    ),
    DataNeedNode(
        need_id="dn.task.trajectory_to_road.input",
        task_id="task.trajectory_to_road",
        data_type_id="dt.trajectory.raw",
        direction="consumes",
        required=True,
        description="Reserved trajectory seam consumes raw trajectories.",
        metadata=_closure_metadata(claim_state="reservation_only", runtime_role="data_need"),
    ),
    DataNeedNode(
        need_id="dn.task.trajectory_to_road.output",
        task_id="task.trajectory_to_road",
        data_type_id="dt.road.candidate",
        direction="produces",
        required=True,
        description="Reserved trajectory seam produces road candidates.",
        metadata=_closure_metadata(claim_state="reservation_only", runtime_role="data_need"),
    ),
]


REPAIR_STRATEGIES: Dict[str, RepairStrategyNode] = {
    "repair.alternative_algorithm.v1": RepairStrategyNode(
        strategy_id="repair.alternative_algorithm.v1",
        strategy_name="Alternative Algorithm Fallback",
        reason_codes=["primary_execution_failed", "alternative_algorithm_succeeded"],
        applies_to_task_ids=["task.building.fusion", "task.road.fusion", "task.waterways.fusion"],
        metadata=_closure_metadata(
            claim_state="runtime_supported",
            runtime_role="repair_strategy",
            strategy="alternative_algorithm",
        ),
    ),
    "repair.source_fallback.v1": RepairStrategyNode(
        strategy_id="repair.source_fallback.v1",
        strategy_name="Alternative Source Fallback",
        reason_codes=["source_fallback_selected", "fallback_when_no_safe_reuse_candidate"],
        applies_to_task_ids=[
            "task.building.fusion",
            "task.road.fusion",
            "task.water.fusion",
            "task.waterways.fusion",
            "task.poi.fusion",
        ],
        metadata=_closure_metadata(
            claim_state="runtime_supported",
            runtime_role="repair_strategy",
            strategy="alternative_source",
        ),
    ),
}


TASK_BUNDLES: Dict[str, TaskBundleNode] = {
    "task_bundle.direct_request": TaskBundleNode(
        bundle_id="task_bundle.direct_request",
        bundle_name="Direct Task Request Bundle",
        requested_tasks=[
            "task.building.fusion",
            "task.road.fusion",
            "task.water.fusion",
            "task.waterways.fusion",
            "task.poi.fusion",
        ],
        qos_policy_id="qos.task.default.v1",
        data_need_ids=[
            "dn.task.building.fusion.input",
            "dn.task.road.fusion.input",
            "dn.task.water.fusion.input",
            "dn.task.waterways.fusion.input",
            "dn.task.poi.fusion.input",
        ],
        repair_strategy_ids=["repair.source_fallback.v1", "repair.alternative_algorithm.v1"],
        requires_disaster_profile=False,
        metadata=_closure_metadata(
            claim_state="runtime_supported",
            runtime_role="task_bundle",
            entry_mode="task_driven",
        ),
    ),
    "task_bundle.flood.building_road": TaskBundleNode(
        bundle_id="task_bundle.flood.building_road",
        bundle_name="Flood Building And Road Bundle",
        requested_tasks=["task.building.fusion", "task.road.fusion"],
        qos_policy_id="qos.scenario.flood.v1",
        output_requirement_id="or.building.fused.v1",
        data_need_ids=["dn.task.building.fusion.input", "dn.task.road.fusion.input"],
        repair_strategy_ids=["repair.source_fallback.v1", "repair.alternative_algorithm.v1"],
        requires_disaster_profile=True,
        metadata=_closure_metadata(
            claim_state="runtime_supported",
            runtime_role="task_bundle",
            entry_mode="scenario_driven",
            scenario_profile_id="scenario.flood.default",
        ),
    ),
    "task_bundle.earthquake.building_road": TaskBundleNode(
        bundle_id="task_bundle.earthquake.building_road",
        bundle_name="Earthquake Building And Road Bundle",
        requested_tasks=["task.building.fusion", "task.road.fusion"],
        qos_policy_id="qos.scenario.earthquake.v1",
        output_requirement_id="or.building.fused.v1",
        data_need_ids=["dn.task.building.fusion.input", "dn.task.road.fusion.input"],
        repair_strategy_ids=["repair.source_fallback.v1", "repair.alternative_algorithm.v1"],
        requires_disaster_profile=True,
        metadata=_closure_metadata(
            claim_state="runtime_supported",
            runtime_role="task_bundle",
            entry_mode="scenario_driven",
            scenario_profile_id="scenario.earthquake.default",
        ),
    ),
    "task_bundle.typhoon.building_road": TaskBundleNode(
        bundle_id="task_bundle.typhoon.building_road",
        bundle_name="Typhoon Building And Road Bundle",
        requested_tasks=["task.building.fusion", "task.road.fusion"],
        qos_policy_id="qos.scenario.typhoon.v1",
        output_requirement_id="or.building.fused.v1",
        data_need_ids=["dn.task.building.fusion.input", "dn.task.road.fusion.input"],
        repair_strategy_ids=["repair.source_fallback.v1", "repair.alternative_algorithm.v1"],
        requires_disaster_profile=True,
        metadata=_closure_metadata(
            claim_state="runtime_supported",
            runtime_role="task_bundle",
            entry_mode="scenario_driven",
            scenario_profile_id="scenario.typhoon.default",
        ),
    ),
}


CAN_TRANSFORM_TO: Dict[str, List[str]] = {
    "dt.raw.vector": ["dt.building.bundle", "dt.road.bundle", "dt.waterways.bundle", "dt.poi.bundle"],
    "dt.trajectory.raw": ["dt.road.candidate"],
    "dt.road.candidate": ["dt.road.bundle"],
}


from fusion_algorithms.registry_metadata import (  # noqa: E402
    FUSIONCODE_ALGORITHMS,
    FUSIONCODE_DATA_TYPES,
    FUSIONCODE_PARAMETER_SPECS,
    FUSIONCODE_WORKFLOW_PATTERNS,
)


DATA_TYPES.update(FUSIONCODE_DATA_TYPES)
ALGORITHMS.update(FUSIONCODE_ALGORITHMS)
for _algo_id, _specs in FUSIONCODE_PARAMETER_SPECS.items():
    PARAMETER_SPECS.setdefault(_algo_id, []).extend(_specs)
WORKFLOW_PATTERNS.extend(FUSIONCODE_WORKFLOW_PATTERNS)
