from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Tuple

from kg.models import DataSourceNode


DEFAULT_DISASTER_TYPES = ["generic", "flood", "earthquake", "typhoon"]


@dataclass(frozen=True)
class CatalogBundleSpec:
    source_id: str
    osm_relative_dir: Tuple[str, ...]
    ref_relative_dir: Optional[Tuple[str, ...]]


CATALOG_BUNDLE_SPECS: Tuple[CatalogBundleSpec, ...] = (
    CatalogBundleSpec(
        source_id="catalog.flood.building",
        osm_relative_dir=("Data", "buildings", "OSM"),
        ref_relative_dir=("Data", "buildings", "Google"),
    ),
    CatalogBundleSpec(
        source_id="catalog.flood.road",
        osm_relative_dir=("Data", "roads", "OSM"),
        ref_relative_dir=None,
    ),
    CatalogBundleSpec(
        source_id="catalog.earthquake.building",
        osm_relative_dir=("Data", "buildings", "OSM"),
        ref_relative_dir=("Data", "buildings", "Microsoft"),
    ),
    CatalogBundleSpec(
        source_id="catalog.earthquake.road",
        osm_relative_dir=("Data", "roads", "OSM"),
        ref_relative_dir=None,
    ),
    CatalogBundleSpec(
        source_id="catalog.typhoon.road",
        osm_relative_dir=("Data", "roads", "OSM"),
        ref_relative_dir=None,
    ),
)


def build_data_sources() -> List[DataSourceNode]:
    return [
        DataSourceNode(
            source_id="upload.bundle",
            source_name="Uploaded Bundle",
            supported_types=["dt.building.bundle", "dt.road.bundle", "dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=1.0,
            source_kind="local_upload",
            quality_tier="operator_provided",
            freshness_category="request_bound",
            freshness_hours=0,
            freshness_score=1.0,
            supported_job_types=["building", "road"],
            supported_geometry_types=["mixed", "polygon", "line", "point"],
            metadata={
                "kind": "local",
                "provider_family": "manual_upload",
                "bundle_strategy": "operator_supplied",
            },
        ),
        DataSourceNode(
            source_id="catalog.flood.building",
            source_name="Flood Building Bundle (OSM + Google)",
            supported_types=["dt.building.bundle"],
            disaster_types=["flood", "generic"],
            quality_score=0.86,
            source_kind="catalog",
            quality_tier="curated",
            freshness_category="event_snapshot",
            freshness_hours=72,
            freshness_score=0.74,
            supported_job_types=["building"],
            supported_geometry_types=["polygon"],
            metadata={
                "kind": "catalog",
                "priority": 2,
                "provider_family": "local_bundle_catalog",
                "bundle_strategy": "osm_ref_pair",
                "component_source_ids": ["raw.osm.building", "raw.google.building"],
                "path_hints": ["Data/buildings/OSM", "Data/buildings/Google"],
            },
        ),
        DataSourceNode(
            source_id="catalog.earthquake.building",
            source_name="Earthquake Building Bundle (OSM + Microsoft)",
            supported_types=["dt.building.bundle"],
            disaster_types=["earthquake", "generic"],
            quality_score=0.88,
            source_kind="catalog",
            quality_tier="curated",
            freshness_category="event_snapshot",
            freshness_hours=96,
            freshness_score=0.71,
            supported_job_types=["building"],
            supported_geometry_types=["polygon"],
            metadata={
                "kind": "catalog",
                "priority": 2,
                "provider_family": "local_bundle_catalog",
                "bundle_strategy": "osm_ref_pair",
                "component_source_ids": ["raw.osm.building", "raw.microsoft.building"],
                "path_hints": ["Data/buildings/OSM", "Data/buildings/Microsoft"],
            },
        ),
        DataSourceNode(
            source_id="catalog.flood.road",
            source_name="Flood Road Bundle (OSM Baseline)",
            supported_types=["dt.road.bundle"],
            disaster_types=["flood", "generic"],
            quality_score=0.85,
            source_kind="catalog",
            quality_tier="curated",
            freshness_category="event_snapshot",
            freshness_hours=72,
            freshness_score=0.73,
            supported_job_types=["road"],
            supported_geometry_types=["line"],
            metadata={
                "kind": "catalog",
                "priority": 2,
                "provider_family": "local_bundle_catalog",
                "bundle_strategy": "single_source_with_empty_ref",
                "component_source_ids": ["raw.osm.road"],
                "path_hints": ["Data/roads/OSM"],
            },
        ),
        DataSourceNode(
            source_id="catalog.earthquake.road",
            source_name="Earthquake Road Bundle (OSM Baseline)",
            supported_types=["dt.road.bundle"],
            disaster_types=["earthquake", "generic"],
            quality_score=0.84,
            source_kind="catalog",
            quality_tier="curated",
            freshness_category="event_snapshot",
            freshness_hours=96,
            freshness_score=0.69,
            supported_job_types=["road"],
            supported_geometry_types=["line"],
            metadata={
                "kind": "catalog",
                "priority": 2,
                "provider_family": "local_bundle_catalog",
                "bundle_strategy": "single_source_with_empty_ref",
                "component_source_ids": ["raw.osm.road"],
                "path_hints": ["Data/roads/OSM"],
            },
        ),
        DataSourceNode(
            source_id="catalog.typhoon.road",
            source_name="Typhoon Road Bundle (OSM Baseline)",
            supported_types=["dt.road.bundle"],
            disaster_types=["typhoon", "generic"],
            quality_score=0.87,
            source_kind="catalog",
            quality_tier="curated",
            freshness_category="event_snapshot",
            freshness_hours=48,
            freshness_score=0.78,
            supported_job_types=["road"],
            supported_geometry_types=["line"],
            metadata={
                "kind": "catalog",
                "priority": 2,
                "provider_family": "local_bundle_catalog",
                "bundle_strategy": "single_source_with_empty_ref",
                "component_source_ids": ["raw.osm.road"],
                "path_hints": ["Data/roads/OSM"],
            },
        ),
        DataSourceNode(
            source_id="raw.osm.building",
            source_name="OSM Building Footprints",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.84,
            source_kind="open_data",
            quality_tier="community_curated",
            freshness_category="sample_snapshot",
            freshness_hours=168,
            freshness_score=0.62,
            supported_job_types=["building"],
            supported_geometry_types=["polygon"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "osm",
                "theme": "building",
                "source_role": "osm_primary",
                "path_hint": "Data/buildings/OSM",
            },
        ),
        DataSourceNode(
            source_id="raw.google.building",
            source_name="Google Open Buildings",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.87,
            source_kind="open_data",
            quality_tier="foundation_model_extracted",
            freshness_category="sample_snapshot",
            freshness_hours=240,
            freshness_score=0.58,
            supported_job_types=["building"],
            supported_geometry_types=["polygon"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "google",
                "theme": "building",
                "source_role": "reference_candidate",
                "path_hint": "Data/buildings/Google",
            },
        ),
        DataSourceNode(
            source_id="raw.microsoft.building",
            source_name="Microsoft Building Footprints",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.88,
            source_kind="open_data",
            quality_tier="provider_curated",
            freshness_category="sample_snapshot",
            freshness_hours=240,
            freshness_score=0.59,
            supported_job_types=["building"],
            supported_geometry_types=["polygon"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "microsoft",
                "theme": "building",
                "source_role": "reference_candidate",
                "path_hint": "Data/buildings/Microsoft",
            },
        ),
        DataSourceNode(
            source_id="raw.osm.road",
            source_name="OSM Road Network",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.82,
            source_kind="open_data",
            quality_tier="community_curated",
            freshness_category="sample_snapshot",
            freshness_hours=168,
            freshness_score=0.63,
            supported_job_types=["road"],
            supported_geometry_types=["line"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "osm",
                "theme": "road",
                "source_role": "osm_primary",
                "path_hint": "Data/roads/OSM",
            },
        ),
        DataSourceNode(
            source_id="raw.osm.water",
            source_name="OSM Water Features",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.8,
            source_kind="open_data",
            quality_tier="community_curated",
            freshness_category="sample_snapshot",
            freshness_hours=168,
            freshness_score=0.61,
            supported_job_types=["building", "road"],
            supported_geometry_types=["polygon", "line"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "osm",
                "theme": "water",
                "source_role": "environmental_context",
                "path_hint": "Data/burundi-260127-free.shp/gis_osm_water_a_free_1.shp",
            },
        ),
        DataSourceNode(
            source_id="raw.local.water",
            source_name="Local Open Water Sample",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.79,
            source_kind="open_data",
            quality_tier="local_sample",
            freshness_category="sample_snapshot",
            freshness_hours=240,
            freshness_score=0.55,
            supported_job_types=["building", "road"],
            supported_geometry_types=["polygon"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "local_open_data",
                "theme": "water",
                "source_role": "environmental_context",
                "path_hint": "Data/water",
            },
        ),
        DataSourceNode(
            source_id="raw.osm.poi",
            source_name="OSM Points Of Interest",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.78,
            source_kind="open_data",
            quality_tier="community_curated",
            freshness_category="sample_snapshot",
            freshness_hours=168,
            freshness_score=0.6,
            supported_job_types=["building", "road"],
            supported_geometry_types=["point", "polygon"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "osm",
                "theme": "poi",
                "source_role": "enrichment_candidate",
                "path_hint": "Data/burundi-260127-free.shp/gis_osm_pois_free_1.shp",
            },
        ),
        DataSourceNode(
            source_id="raw.gns.poi",
            source_name="GNS Place Names",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.81,
            source_kind="open_data",
            quality_tier="gazetteer",
            freshness_category="sample_snapshot",
            freshness_hours=720,
            freshness_score=0.42,
            supported_job_types=["building", "road"],
            supported_geometry_types=["point"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "gns",
                "theme": "poi",
                "source_role": "name_reference",
                "path_hint": "Data/POI/布隆迪/GNS.shp",
            },
        ),
        DataSourceNode(
            source_id="raw.rh.poi",
            source_name="RH Points Of Interest",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.76,
            source_kind="open_data",
            quality_tier="local_sample",
            freshness_category="sample_snapshot",
            freshness_hours=720,
            freshness_score=0.4,
            supported_job_types=["building", "road"],
            supported_geometry_types=["point"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "rh",
                "theme": "poi",
                "source_role": "reference_candidate",
                "path_hint": "Data/POI/布隆迪/RH.shp",
            },
        ),
    ]
