from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Tuple

from kg.models import DataSourceNode
from kg.track_b_source_contract import track_b_source_metadata, track_b_theme_metadata


DEFAULT_DISASTER_TYPES = ["generic", "flood", "earthquake", "typhoon"]


@dataclass(frozen=True)
class CatalogBundleSpec:
    source_id: str
    osm_source_id: str
    ref_source_id: Optional[str]
    bundle_strategy: str

    @property
    def component_source_ids(self) -> Tuple[str, ...]:
        if self.ref_source_id is None:
            return (self.osm_source_id,)
        return (self.osm_source_id, self.ref_source_id)


@dataclass(frozen=True)
class RawVectorSourceSpec:
    source_id: str
    locator_kind: str
    relative_path: Tuple[str, ...]
    glob_pattern: Optional[str] = None

    @property
    def path_hint(self) -> str:
        prefix = "/".join(self.relative_path)
        if self.glob_pattern:
            return f"{prefix}/{self.glob_pattern}"
        return prefix


RAW_VECTOR_SOURCE_SPECS: Tuple[RawVectorSourceSpec, ...] = (
    RawVectorSourceSpec(
        source_id="raw.osm.building",
        locator_kind="first_shp_in_dir",
        relative_path=("Data", "buildings", "OSM"),
    ),
    RawVectorSourceSpec(
        source_id="raw.google.building",
        locator_kind="first_shp_in_dir",
        relative_path=("Data", "buildings", "Google"),
    ),
    RawVectorSourceSpec(
        source_id="raw.microsoft.building",
        locator_kind="first_shp_in_dir",
        relative_path=("Data", "buildings", "Microsoft"),
    ),
    RawVectorSourceSpec(
        source_id="raw.openbuildingmap.building",
        locator_kind="first_shp_in_dir",
        relative_path=("Data", "buildings", "OpenBuildingMap"),
    ),
    RawVectorSourceSpec(
        source_id="raw.local.microsoft.building",
        locator_kind="first_shp_in_dir",
        relative_path=("Data", "buildings", "MicrosoftLocal"),
    ),
    RawVectorSourceSpec(
        source_id="raw.google.open_buildings.vector",
        locator_kind="first_shp_in_dir",
        relative_path=("Data", "buildings", "GoogleOpenBuildingsVector"),
    ),
    RawVectorSourceSpec(
        source_id="raw.osm.road",
        locator_kind="first_shp_in_dir",
        relative_path=("Data", "roads", "OSM"),
    ),
    RawVectorSourceSpec(
        source_id="raw.microsoft.road",
        locator_kind="first_shp_in_dir",
        relative_path=("Data", "roads", "Microsoft"),
    ),
    RawVectorSourceSpec(
        source_id="raw.overture.road",
        locator_kind="first_shp_in_dir",
        relative_path=("Data", "roads", "Overture"),
    ),
    RawVectorSourceSpec(
        source_id="raw.overture.transportation",
        locator_kind="first_shp_in_dir",
        relative_path=("Data", "roads", "Overture"),
    ),
    RawVectorSourceSpec(
        source_id="raw.osm.water",
        locator_kind="exact_path",
        relative_path=("Data", "burundi-260127-free.shp", "gis_osm_water_a_free_1.shp"),
    ),
    RawVectorSourceSpec(
        source_id="raw.osm.waterways",
        locator_kind="exact_path",
        relative_path=("Data", "burundi-260127-free.shp", "gis_osm_waterways_free_1.shp"),
    ),
    RawVectorSourceSpec(
        source_id="raw.local.pakistan.waterways",
        locator_kind="exact_path",
        relative_path=("Data", "water", "Pakistan_Waterways_Data.shp"),
    ),
    RawVectorSourceSpec(
        source_id="raw.local.water",
        locator_kind="exact_path",
        relative_path=("Data", "water", "布隆迪湖泊.shp"),
    ),
    RawVectorSourceSpec(
        source_id="raw.hydrorivers.water",
        locator_kind="exact_path",
        relative_path=("Data", "water", "HydroRIVERS_v10.shp"),
    ),
    RawVectorSourceSpec(
        source_id="raw.hydrolakes.water",
        locator_kind="exact_path",
        relative_path=("Data", "water", "HydroLAKES_polys_v10.shp"),
    ),
    RawVectorSourceSpec(
        source_id="raw.osm.poi",
        locator_kind="exact_path",
        relative_path=("Data", "burundi-260127-free.shp", "gis_osm_pois_free_1.shp"),
    ),
    RawVectorSourceSpec(
        source_id="raw.gns.poi",
        locator_kind="recursive_glob",
        relative_path=("Data", "POI"),
        glob_pattern="**/GNS.shp",
    ),
    RawVectorSourceSpec(
        source_id="raw.google.poi",
        locator_kind="recursive_glob",
        relative_path=("Data", "POI"),
        glob_pattern="**/Google*.shp",
    ),
    RawVectorSourceSpec(
        source_id="raw.rh.poi",
        locator_kind="recursive_glob",
        relative_path=("Data", "POI"),
        glob_pattern="**/RH.shp",
    ),
)

RAW_VECTOR_SOURCE_SPECS_BY_ID = {spec.source_id: spec for spec in RAW_VECTOR_SOURCE_SPECS}

CATALOG_BUNDLE_SPECS: Tuple[CatalogBundleSpec, ...] = (
    CatalogBundleSpec(
        source_id="catalog.flood.building",
        osm_source_id="raw.osm.building",
        ref_source_id="raw.microsoft.building",
        bundle_strategy="osm_ref_pair",
    ),
    CatalogBundleSpec(
        source_id="catalog.flood.water",
        osm_source_id="raw.osm.water",
        ref_source_id="raw.hydrolakes.water",
        bundle_strategy="osm_ref_pair",
    ),
    CatalogBundleSpec(
        source_id="catalog.flood.water_polygon",
        osm_source_id="raw.osm.water",
        ref_source_id="raw.hydrolakes.water",
        bundle_strategy="osm_ref_pair",
    ),
    CatalogBundleSpec(
        source_id="catalog.flood.waterways",
        osm_source_id="raw.osm.waterways",
        ref_source_id="raw.local.pakistan.waterways",
        bundle_strategy="osm_ref_pair",
    ),
    CatalogBundleSpec(
        source_id="catalog.generic.poi",
        osm_source_id="raw.osm.poi",
        ref_source_id="raw.gns.poi",
        bundle_strategy="osm_ref_pair",
    ),
    CatalogBundleSpec(
        source_id="catalog.flood.road",
        osm_source_id="raw.osm.road",
        ref_source_id="raw.microsoft.road",
        bundle_strategy="osm_ref_pair",
    ),
    CatalogBundleSpec(
        source_id="catalog.earthquake.building",
        osm_source_id="raw.osm.building",
        ref_source_id="raw.microsoft.building",
        bundle_strategy="osm_ref_pair",
    ),
    CatalogBundleSpec(
        source_id="catalog.earthquake.road",
        osm_source_id="raw.osm.road",
        ref_source_id="raw.microsoft.road",
        bundle_strategy="osm_ref_pair",
    ),
    CatalogBundleSpec(
        source_id="catalog.typhoon.road",
        osm_source_id="raw.osm.road",
        ref_source_id="raw.microsoft.road",
        bundle_strategy="osm_ref_pair",
    ),
)

CATALOG_BUNDLE_SPECS_BY_ID = {spec.source_id: spec for spec in CATALOG_BUNDLE_SPECS}


def get_raw_vector_source_spec(source_id: str) -> RawVectorSourceSpec:
    try:
        return RAW_VECTOR_SOURCE_SPECS_BY_ID[source_id]
    except KeyError as exc:
        raise KeyError(f"Unknown raw vector source: {source_id}") from exc


def get_catalog_bundle_spec(source_id: str) -> CatalogBundleSpec:
    try:
        return CATALOG_BUNDLE_SPECS_BY_ID[source_id]
    except KeyError as exc:
        raise KeyError(f"Unknown catalog bundle source: {source_id}") from exc


def _bundle_path_hints(bundle_spec: CatalogBundleSpec) -> List[str]:
    return [get_raw_vector_source_spec(source_id).path_hint for source_id in bundle_spec.component_source_ids]


def _raw_path_hint(source_id: str) -> str:
    return get_raw_vector_source_spec(source_id).path_hint


def _bundle_component_ids(source_id: str) -> List[str]:
    return list(get_catalog_bundle_spec(source_id).component_source_ids)


def _bundle_strategy(source_id: str) -> str:
    return get_catalog_bundle_spec(source_id).bundle_strategy


def build_data_sources() -> List[DataSourceNode]:
    return [
        DataSourceNode(
            source_id="upload.bundle",
            source_name="Uploaded Bundle",
            supported_types=[
                "dt.building.bundle",
                "dt.building.source_set",
                "dt.building.normalized_set",
                "dt.building.presence_validated_set",
                "dt.building.fused_raw",
                "dt.building.conflict_optimized",
                "dt.raster.building_presence",
                "dt.raster.building_height",
                "dt.road.network",
                "dt.road.bundle",
                "dt.waterways.bundle",
                "dt.trajectory.raw",
                "dt.road.candidate",
                "dt.water.bundle",
                "dt.poi.bundle",
                "dt.raw.vector",
            ],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=1.0,
            source_kind="local_upload",
            quality_tier="operator_provided",
            freshness_category="request_bound",
            freshness_hours=0,
            freshness_score=1.0,
            supported_job_types=["building", "road", "water", "poi"],
            supported_geometry_types=["mixed", "polygon", "line", "point"],
            metadata={
                "kind": "local",
                "provider_family": "manual_upload",
                "bundle_strategy": "operator_supplied",
                "reserved_transform_inputs": ["dt.trajectory.raw", "dt.road.candidate"],
                "source_form": "mixed",
                "runtime_status": "runtime_candidate",
                "selectable_now": True,
            },
        ),
        DataSourceNode(
            source_id="catalog.flood.building",
            source_name="Flood Building Bundle (OSM + Microsoft)",
            supported_types=["dt.building.bundle"],
            disaster_types=["flood", "generic"],
            quality_score=0.86,
            source_kind="catalog",
            quality_tier="curated",
            freshness_category="event_snapshot",
            freshness_hours=72,
            freshness_score=0.74,
            supported_job_types=["building"],
            supported_geometry_types=["polygon"],
            metadata={
                "kind": "catalog",
                "priority": 2,
                "provider_family": "local_bundle_catalog",
                "bundle_strategy": _bundle_strategy("catalog.flood.building"),
                "component_source_ids": _bundle_component_ids("catalog.flood.building"),
                "path_hints": _bundle_path_hints(get_catalog_bundle_spec("catalog.flood.building")),
                "supports_aoi": True,
                "materialization_scope": "resolved_aoi_clip",
                "source_form": "bundle",
                "runtime_status": "runtime_candidate",
                "selectable_now": True,
                "supports_tiling": True,
                "height_semantics": "confidence_only",
                **track_b_theme_metadata("building"),
            },
        ),
        DataSourceNode(
            source_id="catalog.flood.water",
            source_name="Flood Water Bundle (OSM + HydroLAKES)",
            supported_types=["dt.water.bundle"],
            disaster_types=["flood", "generic"],
            quality_score=0.84,
            source_kind="catalog",
            quality_tier="curated",
            freshness_category="event_snapshot",
            freshness_hours=72,
            freshness_score=0.71,
            supported_job_types=["water"],
            supported_geometry_types=["polygon"],
            metadata={
                "kind": "catalog",
                "priority": 2,
                "provider_family": "local_bundle_catalog",
                "bundle_strategy": _bundle_strategy("catalog.flood.water"),
                "component_source_ids": _bundle_component_ids("catalog.flood.water"),
                "path_hints": _bundle_path_hints(get_catalog_bundle_spec("catalog.flood.water")),
                "supports_aoi": True,
                "materialization_scope": "resolved_aoi_clip",
                "source_form": "bundle",
                "runtime_status": "runtime_candidate",
                "selectable_now": True,
                **track_b_theme_metadata("water"),
                "reference_boundary": "polygon_only",
            },
        ),
        DataSourceNode(
            source_id="catalog.flood.water_polygon",
            source_name="Flood Water Polygon Bundle (OSM + HydroLAKES)",
            supported_types=["dt.water.bundle"],
            disaster_types=["flood", "generic"],
            quality_score=0.84,
            source_kind="catalog",
            quality_tier="curated",
            freshness_category="event_snapshot",
            freshness_hours=72,
            freshness_score=0.71,
            supported_job_types=["water"],
            supported_geometry_types=["polygon"],
            metadata={
                "kind": "catalog",
                "priority": 2,
                "provider_family": "local_bundle_catalog",
                "bundle_strategy": _bundle_strategy("catalog.flood.water_polygon"),
                "component_source_ids": _bundle_component_ids("catalog.flood.water_polygon"),
                "path_hints": _bundle_path_hints(get_catalog_bundle_spec("catalog.flood.water_polygon")),
                "supports_aoi": True,
                "materialization_scope": "resolved_aoi_clip",
                "source_form": "bundle",
                "runtime_status": "runtime_candidate",
                "selectable_now": True,
                **track_b_theme_metadata("water"),
                "reference_boundary": "polygon_only",
            },
        ),
        DataSourceNode(
            source_id="catalog.flood.waterways",
            source_name="Flood Waterways Bundle (OSM + Pakistan Local Waterways)",
            supported_types=["dt.waterways.bundle"],
            disaster_types=["flood", "generic"],
            quality_score=0.8,
            source_kind="catalog",
            quality_tier="curated",
            freshness_category="event_snapshot",
            freshness_hours=72,
            freshness_score=0.68,
            supported_job_types=["water"],
            supported_geometry_types=["line"],
            metadata={
                "kind": "catalog",
                "priority": 2,
                "provider_family": "local_bundle_catalog",
                "bundle_strategy": _bundle_strategy("catalog.flood.waterways"),
                "component_source_ids": _bundle_component_ids("catalog.flood.waterways"),
                "path_hints": _bundle_path_hints(get_catalog_bundle_spec("catalog.flood.waterways")),
                "supports_aoi": True,
                "materialization_scope": "resolved_aoi_clip",
                "source_form": "bundle",
                "runtime_status": "runtime_candidate",
                "selectable_now": True,
                "water_semantics": "waterways_line",
                **track_b_theme_metadata("waterways"),
            },
        ),
        DataSourceNode(
            source_id="catalog.generic.poi",
            source_name="Generic POI Bundle (OSM + GNS)",
            supported_types=["dt.poi.bundle"],
            disaster_types=["generic"],
            quality_score=0.82,
            source_kind="catalog",
            quality_tier="curated",
            freshness_category="sample_snapshot",
            freshness_hours=168,
            freshness_score=0.61,
            supported_job_types=["poi"],
            supported_geometry_types=["point"],
            metadata={
                "kind": "catalog",
                "priority": 2,
                "provider_family": "local_bundle_catalog",
                "bundle_strategy": _bundle_strategy("catalog.generic.poi"),
                "component_source_ids": _bundle_component_ids("catalog.generic.poi"),
                "path_hints": _bundle_path_hints(get_catalog_bundle_spec("catalog.generic.poi")),
                "supports_aoi": True,
                "materialization_scope": "resolved_aoi_clip",
                "source_form": "bundle",
                "runtime_status": "runtime_candidate",
                "selectable_now": True,
                **track_b_theme_metadata("poi"),
            },
        ),
        DataSourceNode(
            source_id="catalog.earthquake.building",
            source_name="Earthquake Building Bundle (OSM + Microsoft)",
            supported_types=["dt.building.bundle"],
            disaster_types=["earthquake", "generic"],
            quality_score=0.88,
            source_kind="catalog",
            quality_tier="curated",
            freshness_category="event_snapshot",
            freshness_hours=96,
            freshness_score=0.71,
            supported_job_types=["building"],
            supported_geometry_types=["polygon"],
            metadata={
                "kind": "catalog",
                "priority": 2,
                "provider_family": "local_bundle_catalog",
                "bundle_strategy": _bundle_strategy("catalog.earthquake.building"),
                "component_source_ids": _bundle_component_ids("catalog.earthquake.building"),
                "path_hints": _bundle_path_hints(get_catalog_bundle_spec("catalog.earthquake.building")),
                "supports_aoi": True,
                "materialization_scope": "resolved_aoi_clip",
                "source_form": "bundle",
                "runtime_status": "runtime_candidate",
                "selectable_now": True,
                "supports_tiling": True,
                "height_semantics": "confidence_only",
                **track_b_theme_metadata("building"),
            },
        ),
        DataSourceNode(
            source_id="catalog.flood.road",
            source_name="Flood Road Bundle (OSM + Microsoft)",
            supported_types=["dt.road.bundle"],
            disaster_types=["flood", "generic"],
            quality_score=0.86,
            source_kind="catalog",
            quality_tier="curated",
            freshness_category="event_snapshot",
            freshness_hours=72,
            freshness_score=0.74,
            supported_job_types=["road"],
            supported_geometry_types=["line"],
            metadata={
                "kind": "catalog",
                "priority": 2,
                "provider_family": "local_bundle_catalog",
                "bundle_strategy": _bundle_strategy("catalog.flood.road"),
                "component_source_ids": _bundle_component_ids("catalog.flood.road"),
                "path_hints": _bundle_path_hints(get_catalog_bundle_spec("catalog.flood.road")),
                "supports_aoi": True,
                "materialization_scope": "resolved_aoi_clip",
                "source_form": "bundle",
                "runtime_status": "runtime_candidate",
                "selectable_now": True,
                **track_b_theme_metadata("road"),
                "reference_boundary": "secondary_reference_now",
            },
        ),
        DataSourceNode(
            source_id="catalog.earthquake.road",
            source_name="Earthquake Road Bundle (OSM + Microsoft)",
            supported_types=["dt.road.bundle"],
            disaster_types=["earthquake", "generic"],
            quality_score=0.85,
            source_kind="catalog",
            quality_tier="curated",
            freshness_category="event_snapshot",
            freshness_hours=96,
            freshness_score=0.7,
            supported_job_types=["road"],
            supported_geometry_types=["line"],
            metadata={
                "kind": "catalog",
                "priority": 2,
                "provider_family": "local_bundle_catalog",
                "bundle_strategy": _bundle_strategy("catalog.earthquake.road"),
                "component_source_ids": _bundle_component_ids("catalog.earthquake.road"),
                "path_hints": _bundle_path_hints(get_catalog_bundle_spec("catalog.earthquake.road")),
                "supports_aoi": True,
                "materialization_scope": "resolved_aoi_clip",
                "source_form": "bundle",
                "runtime_status": "runtime_candidate",
                "selectable_now": True,
                **track_b_theme_metadata("road"),
                "reference_boundary": "secondary_reference_now",
            },
        ),
        DataSourceNode(
            source_id="catalog.typhoon.road",
            source_name="Typhoon Road Bundle (OSM + Microsoft)",
            supported_types=["dt.road.bundle"],
            disaster_types=["typhoon", "generic"],
            quality_score=0.88,
            source_kind="catalog",
            quality_tier="curated",
            freshness_category="event_snapshot",
            freshness_hours=48,
            freshness_score=0.79,
            supported_job_types=["road"],
            supported_geometry_types=["line"],
            metadata={
                "kind": "catalog",
                "priority": 2,
                "provider_family": "local_bundle_catalog",
                "bundle_strategy": _bundle_strategy("catalog.typhoon.road"),
                "component_source_ids": _bundle_component_ids("catalog.typhoon.road"),
                "path_hints": _bundle_path_hints(get_catalog_bundle_spec("catalog.typhoon.road")),
                "supports_aoi": True,
                "materialization_scope": "resolved_aoi_clip",
                "source_form": "bundle",
                "runtime_status": "runtime_candidate",
                "selectable_now": True,
                **track_b_theme_metadata("road"),
                "reference_boundary": "secondary_reference_now",
            },
        ),
        DataSourceNode(
            source_id="raw.osm.building",
            source_name="OSM Building Footprints",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.84,
            source_kind="open_data",
            quality_tier="community_curated",
            freshness_category="sample_snapshot",
            freshness_hours=168,
            freshness_score=0.62,
            supported_job_types=["building"],
            supported_geometry_types=["polygon"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "osm",
                "theme": "building",
                "source_role": "osm_primary",
                "path_hint": _raw_path_hint("raw.osm.building"),
                "supports_aoi": True,
                "materialization_scope": "country_bundle_then_clip",
                "materialization_provider": "geofabrik",
                "source_form": "vector",
                "runtime_status": "runtime_candidate",
                "selectable_now": True,
                "supports_tiling": True,
                "height_semantics": "unknown",
                "coverage_scope": "country_bundle",
                **track_b_source_metadata("raw.osm.building"),
            },
        ),
        DataSourceNode(
            source_id="raw.google.building",
            source_name="Google Open Buildings",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.87,
            source_kind="open_data",
            quality_tier="foundation_model_extracted",
            freshness_category="sample_snapshot",
            freshness_hours=240,
            freshness_score=0.58,
            supported_job_types=["building"],
            supported_geometry_types=["polygon"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "google",
                "theme": "building",
                "source_role": "reference_candidate",
                "path_hint": _raw_path_hint("raw.google.building"),
                "supports_aoi": True,
                "materialization_scope": "resolved_aoi_clip",
                "materialization_provider": "google_open_buildings",
                "source_form": "vector",
                "runtime_status": "runtime_candidate",
                "selectable_now": True,
                "supports_tiling": True,
                "height_semantics": "unknown",
                "coverage_scope": "url_index_then_aoi_clip",
                **track_b_source_metadata("raw.google.building"),
            },
        ),
        DataSourceNode(
            source_id="raw.microsoft.building",
            source_name="Microsoft Building Footprints",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.88,
            source_kind="open_data",
            quality_tier="provider_curated",
            freshness_category="sample_snapshot",
            freshness_hours=240,
            freshness_score=0.59,
            supported_job_types=["building"],
            supported_geometry_types=["polygon"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "microsoft",
                "theme": "building",
                "source_role": "reference_candidate",
                "path_hint": _raw_path_hint("raw.microsoft.building"),
                "supports_aoi": True,
                "materialization_scope": "country_tiles_then_clip",
                "materialization_provider": "microsoft_global_buildings",
                "source_form": "vector",
                "runtime_status": "runtime_candidate",
                "selectable_now": True,
                "supports_tiling": True,
                "height_fields": ["height"],
                "height_semantics": "estimated_height",
                "coverage_scope": "country_tiles",
                **track_b_source_metadata("raw.microsoft.building"),
            },
        ),
        DataSourceNode(
            source_id="raw.openbuildingmap.building",
            source_name="OpenBuildingMap Building Footprints",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.9,
            source_kind="open_data",
            quality_tier="provider_curated",
            freshness_category="sample_snapshot",
            freshness_hours=240,
            freshness_score=0.6,
            supported_job_types=["building"],
            supported_geometry_types=["polygon"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "openbuildingmap",
                "theme": "building",
                "source_role": "reference_candidate",
                "path_hint": "Benin/final_shp/openbuildingmap/openbuildingmap_benin.shp",
                "supports_aoi": False,
                "materialization_scope": "reservation_only",
                "source_form": "vector",
                "runtime_status": "reservation_only",
                "selectable_now": False,
                "supports_tiling": True,
                "height_fields": ["height"],
                "height_semantics": "estimated_height",
                "coverage_scope": "national_clip",
                **track_b_source_metadata("raw.openbuildingmap.building"),
            },
        ),
        DataSourceNode(
            source_id="raw.local.microsoft.building",
            source_name="Local Microsoft Building Footprints",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.89,
            source_kind="open_data",
            quality_tier="local_curated",
            freshness_category="sample_snapshot",
            freshness_hours=240,
            freshness_score=0.58,
            supported_job_types=["building"],
            supported_geometry_types=["polygon"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "microsoft_local",
                "theme": "building",
                "source_role": "reference_candidate",
                "path_hint": "Benin/final_shp/microsoft_global_ml_building_footprints/Microsoft_benin.shp",
                "supports_aoi": False,
                "materialization_scope": "reservation_only",
                "source_form": "vector",
                "runtime_status": "reservation_only",
                "selectable_now": False,
                "supports_tiling": True,
                "height_fields": ["height"],
                "height_semantics": "estimated_height",
                "coverage_scope": "national_clip",
                **track_b_source_metadata("raw.local.microsoft.building"),
            },
        ),
        DataSourceNode(
            source_id="raw.google.open_buildings.vector",
            source_name="Google Open Buildings Vector",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.87,
            source_kind="open_data",
            quality_tier="foundation_model_extracted",
            freshness_category="sample_snapshot",
            freshness_hours=240,
            freshness_score=0.57,
            supported_job_types=["building"],
            supported_geometry_types=["polygon"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "google_open_buildings",
                "theme": "building",
                "source_role": "reference_candidate",
                "path_hint": "Benin/final_shp/google_open_buildings_v3/google_open_buildings_v3_benin.shp",
                "supports_aoi": False,
                "materialization_scope": "reservation_only",
                "source_form": "vector",
                "runtime_status": "reservation_only",
                "selectable_now": False,
                "supports_tiling": True,
                "height_semantics": "unknown",
                "coverage_scope": "national_clip",
                **track_b_source_metadata("raw.google.open_buildings.vector"),
            },
        ),
        DataSourceNode(
            source_id="raw.google.building_presence.raster",
            source_name="Google Building Presence Raster",
            supported_types=["dt.raster.building_presence"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.78,
            source_kind="open_data",
            quality_tier="foundation_model_extracted",
            freshness_category="sample_snapshot",
            freshness_hours=240,
            freshness_score=0.5,
            supported_job_types=["building"],
            supported_geometry_types=["raster"],
            metadata={
                "kind": "raw_raster",
                "provider_family": "google_temporal",
                "theme": "building",
                "source_role": "height_signal_candidate",
                "path_hint": "Benin/_processing/google_open_buildings_temporal_2023/building_presence_2023_benin_4m.tif",
                "supports_aoi": False,
                "materialization_scope": "reservation_only",
                "source_form": "raster",
                "runtime_status": "reservation_only",
                "selectable_now": False,
                "supports_tiling": True,
                "height_semantics": "presence_only",
                "coverage_scope": "national_clip",
            },
        ),
        DataSourceNode(
            source_id="raw.google.building_height.raster",
            source_name="Google Building Height Raster",
            supported_types=["dt.raster.building_height"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.76,
            source_kind="open_data",
            quality_tier="foundation_model_extracted",
            freshness_category="sample_snapshot",
            freshness_hours=240,
            freshness_score=0.5,
            supported_job_types=["building"],
            supported_geometry_types=["raster"],
            metadata={
                "kind": "raw_raster",
                "provider_family": "google_temporal",
                "theme": "building",
                "source_role": "height_enrichment_candidate",
                "path_hint": "Benin/_processing/google_open_buildings_temporal_2023/building_height_2023_benin_4m.tif",
                "supports_aoi": False,
                "materialization_scope": "reservation_only",
                "source_form": "raster",
                "runtime_status": "reservation_only",
                "selectable_now": False,
                "supports_tiling": True,
                "height_semantics": "estimated_height",
                "coverage_scope": "national_clip",
            },
        ),
        DataSourceNode(
            source_id="raw.google.open_buildings_2_5d.height_raster",
            source_name="Open Buildings 2.5D Height Raster",
            supported_types=["dt.raster.building_height"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.88,
            source_kind="open_data",
            quality_tier="foundation_model_extracted",
            freshness_category="sample_snapshot",
            freshness_hours=240,
            freshness_score=0.6,
            supported_job_types=["building"],
            supported_geometry_types=["raster"],
            metadata={
                "kind": "raw_raster",
                "provider_family": "google_open_buildings_2_5d",
                "theme": "building",
                "source_role": "preferred_height_enrichment_candidate",
                "path_hint": "Data/buildings/height/OpenBuildings2_5D",
                "supports_aoi": True,
                "materialization_scope": "source_acquisition_skill",
                "source_form": "raster",
                "runtime_status": "runtime_candidate",
                "selectable_now": True,
                "source_acquisition_skill": "skill.source_acquisition.building_height_raster",
                "rapid_response_timeout_env": "GEOFUSION_HEIGHT_RASTER_MAX_SECONDS",
                "local_path_env": "GEOFUSION_HEIGHT_RASTER_OPEN_BUILDINGS_2_5D_PATH",
                "url_env": "GEOFUSION_HEIGHT_RASTER_OPEN_BUILDINGS_2_5D_URL",
                "supports_tiling": True,
                "height_semantics": "estimated_height",
                "height_priority": 10,
                "rapid_response_fallback": "raw.3d_globfp.building_height.raster",
                "coverage_scope": "global_tiles_or_national_clip",
            },
        ),
        DataSourceNode(
            source_id="raw.3d_globfp.building_height.raster",
            source_name="3D-GloBFP Building Height Raster",
            supported_types=["dt.raster.building_height"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.82,
            source_kind="open_data",
            quality_tier="foundation_model_extracted",
            freshness_category="sample_snapshot",
            freshness_hours=240,
            freshness_score=0.55,
            supported_job_types=["building"],
            supported_geometry_types=["raster"],
            metadata={
                "kind": "raw_raster",
                "provider_family": "3d_globfp",
                "theme": "building",
                "source_role": "secondary_height_enrichment_candidate",
                "path_hint": "Data/buildings/height/3D-GloBFP",
                "supports_aoi": True,
                "materialization_scope": "source_acquisition_skill",
                "source_form": "raster",
                "runtime_status": "runtime_candidate",
                "selectable_now": True,
                "source_acquisition_skill": "skill.source_acquisition.building_height_raster",
                "rapid_response_timeout_env": "GEOFUSION_HEIGHT_RASTER_MAX_SECONDS",
                "local_path_env": "GEOFUSION_HEIGHT_RASTER_3D_GLOBFP_PATH",
                "url_env": "GEOFUSION_HEIGHT_RASTER_3D_GLOBFP_URL",
                "supports_tiling": True,
                "height_semantics": "estimated_height",
                "height_priority": 20,
                "rapid_response_fallback": "footprint_fusion_without_height",
                "coverage_scope": "global_tiles_or_national_clip",
            },
        ),
        DataSourceNode(
            source_id="raw.osm.road",
            source_name="OSM Road Network",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.82,
            source_kind="open_data",
            quality_tier="community_curated",
            freshness_category="sample_snapshot",
            freshness_hours=168,
            freshness_score=0.63,
            supported_job_types=["road"],
            supported_geometry_types=["line"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "osm",
                "theme": "road",
                "source_role": "osm_primary",
                "path_hint": _raw_path_hint("raw.osm.road"),
                "supports_aoi": True,
                "materialization_scope": "country_bundle_then_clip",
                "materialization_provider": "geofabrik",
                "source_form": "vector",
                "runtime_status": "runtime_candidate",
                "selectable_now": True,
                **track_b_source_metadata("raw.osm.road"),
            },
        ),
        DataSourceNode(
            source_id="raw.microsoft.road",
            source_name="Microsoft Road Network",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.8,
            source_kind="provider_data",
            quality_tier="provider_curated",
            freshness_category="sample_snapshot",
            freshness_hours=240,
            freshness_score=0.5,
            supported_job_types=["road"],
            supported_geometry_types=["line"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "microsoft",
                "theme": "road",
                "source_role": "reference_candidate",
                "path_hint": _raw_path_hint("raw.microsoft.road"),
                "supports_aoi": False,
                "materialization_scope": "local_only",
                "source_form": "vector",
                "runtime_status": "runtime_candidate",
                "selectable_now": True,
                **track_b_source_metadata("raw.microsoft.road"),
            },
        ),
        DataSourceNode(
            source_id="raw.overture.road",
            source_name="Overture Transportation Extract",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.86,
            source_kind="open_data",
            quality_tier="provider_curated",
            freshness_category="sample_snapshot",
            freshness_hours=240,
            freshness_score=0.57,
            supported_job_types=["road"],
            supported_geometry_types=["line"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "overture",
                "theme": "road",
                "source_role": "reference_candidate",
                "path_hint": _raw_path_hint("raw.overture.road"),
                "supports_aoi": False,
                "materialization_scope": "local_only",
                "source_form": "vector",
                "runtime_status": "reservation_only",
                "selectable_now": False,
                "coverage_scope": "national_clip",
                **track_b_source_metadata("raw.overture.road"),
            },
        ),
        DataSourceNode(
            source_id="raw.overture.transportation",
            source_name="Overture Transportation Segments",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.81,
            source_kind="open_data",
            quality_tier="provider_curated",
            freshness_category="sample_snapshot",
            freshness_hours=168,
            freshness_score=0.62,
            supported_job_types=["road"],
            supported_geometry_types=["line"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "overturemaps",
                "theme": "road",
                "source_role": "compatibility_extra",
                "path_hint": _raw_path_hint("raw.overture.transportation"),
                "supports_aoi": True,
                "materialization_scope": "compatibility_only",
                "materialization_provider": "overturemaps",
                "source_form": "vector",
                "runtime_status": "reservation_only",
                "selectable_now": False,
                "coverage_scope": "latest_release_bbox",
                **track_b_source_metadata("raw.overture.transportation"),
            },
        ),
        DataSourceNode(
            source_id="raw.osm.water",
            source_name="OSM Water Features",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.8,
            source_kind="open_data",
            quality_tier="community_curated",
            freshness_category="sample_snapshot",
            freshness_hours=168,
            freshness_score=0.61,
            supported_job_types=["building", "road", "water"],
            supported_geometry_types=["polygon", "line"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "osm",
                "theme": "water",
                "source_role": "environmental_context",
                "path_hint": _raw_path_hint("raw.osm.water"),
                "supports_aoi": True,
                "materialization_scope": "country_bundle_then_clip",
                "materialization_provider": "geofabrik",
                "source_form": "vector",
                "runtime_status": "runtime_candidate",
                "selectable_now": True,
                **track_b_source_metadata("raw.osm.water"),
            },
        ),
        DataSourceNode(
            source_id="raw.osm.waterways",
            source_name="OSM Waterways",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.8,
            source_kind="open_data",
            quality_tier="community_curated",
            freshness_category="sample_snapshot",
            freshness_hours=168,
            freshness_score=0.61,
            supported_job_types=["water"],
            supported_geometry_types=["line"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "osm",
                "theme": "waterways",
                "source_role": "environmental_context",
                "path_hint": _raw_path_hint("raw.osm.waterways"),
                "supports_aoi": True,
                "materialization_scope": "country_bundle_then_clip",
                "materialization_provider": "geofabrik",
                "source_form": "vector",
                "runtime_status": "runtime_candidate",
                "selectable_now": True,
                **track_b_source_metadata("raw.osm.waterways"),
            },
        ),
        DataSourceNode(
            source_id="raw.local.pakistan.waterways",
            source_name="Pakistan Local Waterways",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.77,
            source_kind="open_data",
            quality_tier="local_sample",
            freshness_category="sample_snapshot",
            freshness_hours=240,
            freshness_score=0.54,
            supported_job_types=["water"],
            supported_geometry_types=["line"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "local_open_data",
                "theme": "waterways",
                "source_role": "supplement_line",
                "path_hint": _raw_path_hint("raw.local.pakistan.waterways"),
                "supports_aoi": False,
                "materialization_scope": "local_only",
                "source_form": "vector",
                "runtime_status": "runtime_candidate",
                "selectable_now": True,
                **track_b_source_metadata("raw.local.pakistan.waterways"),
            },
        ),
        DataSourceNode(
            source_id="raw.local.water",
            source_name="Local Open Water Sample",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.79,
            source_kind="open_data",
            quality_tier="local_sample",
            freshness_category="sample_snapshot",
            freshness_hours=240,
            freshness_score=0.55,
            supported_job_types=["building", "road", "water"],
            supported_geometry_types=["polygon"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "local_open_data",
                "theme": "water",
                "source_role": "reference_candidate",
                "path_hint": _raw_path_hint("raw.local.water"),
                "supports_aoi": False,
                "materialization_scope": "local_only",
                "source_form": "vector",
                "runtime_status": "runtime_candidate",
                "selectable_now": True,
                **track_b_source_metadata("raw.local.water"),
            },
        ),
        DataSourceNode(
            source_id="raw.hydrorivers.water",
            source_name="HydroRIVERS",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.83,
            source_kind="open_data",
            quality_tier="provider_curated",
            freshness_category="sample_snapshot",
            freshness_hours=720,
            freshness_score=0.5,
            supported_job_types=["water"],
            supported_geometry_types=["line"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "hydrosheds",
                "theme": "waterways",
                "source_role": "reference_candidate",
                "path_hint": _raw_path_hint("raw.hydrorivers.water"),
                "supports_aoi": True,
                "materialization_scope": "global_bundle_then_clip",
                "materialization_provider": "hydrorivers",
                "source_form": "vector",
                "runtime_status": "runtime_candidate",
                "selectable_now": True,
                "coverage_scope": "global_bundle",
                **track_b_source_metadata("raw.hydrorivers.water"),
            },
        ),
        DataSourceNode(
            source_id="raw.hydrolakes.water",
            source_name="HydroLAKES",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.82,
            source_kind="open_data",
            quality_tier="provider_curated",
            freshness_category="sample_snapshot",
            freshness_hours=720,
            freshness_score=0.49,
            supported_job_types=["water"],
            supported_geometry_types=["polygon"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "hydrosheds",
                "theme": "water",
                "source_role": "reference_candidate",
                "path_hint": _raw_path_hint("raw.hydrolakes.water"),
                "supports_aoi": True,
                "materialization_scope": "global_bundle_then_clip",
                "materialization_provider": "hydrolakes",
                "source_form": "vector",
                "runtime_status": "runtime_candidate",
                "selectable_now": True,
                "coverage_scope": "global_bundle",
                **track_b_source_metadata("raw.hydrolakes.water"),
            },
        ),
        DataSourceNode(
            source_id="raw.osm.poi",
            source_name="OSM Points Of Interest",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.78,
            source_kind="open_data",
            quality_tier="community_curated",
            freshness_category="sample_snapshot",
            freshness_hours=168,
            freshness_score=0.6,
            supported_job_types=["building", "road", "poi"],
            supported_geometry_types=["point"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "osm",
                "theme": "poi",
                "source_role": "osm_primary",
                "path_hint": _raw_path_hint("raw.osm.poi"),
                "supports_aoi": True,
                "materialization_scope": "country_bundle_then_clip",
                "materialization_provider": "geofabrik",
                "source_form": "vector",
                "runtime_status": "runtime_candidate",
                "selectable_now": True,
                **track_b_source_metadata("raw.osm.poi"),
            },
        ),
        DataSourceNode(
            source_id="raw.gns.poi",
            source_name="GNS Place Names",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.81,
            source_kind="open_data",
            quality_tier="gazetteer",
            freshness_category="sample_snapshot",
            freshness_hours=720,
            freshness_score=0.42,
            supported_job_types=["building", "road", "poi"],
            supported_geometry_types=["point"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "gns",
                "theme": "poi",
                "source_role": "reference_candidate",
                "path_hint": _raw_path_hint("raw.gns.poi"),
                "supports_aoi": False,
                "materialization_scope": "local_only",
                "source_form": "vector",
                "runtime_status": "runtime_candidate",
                "selectable_now": True,
                **track_b_source_metadata("raw.gns.poi"),
            },
        ),
        DataSourceNode(
            source_id="raw.google.poi",
            source_name="Google Places POI",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.84,
            source_kind="authorized_data",
            quality_tier="provider_curated",
            freshness_category="runtime_query",
            freshness_hours=24,
            freshness_score=0.82,
            supported_job_types=["building", "road", "poi"],
            supported_geometry_types=["point"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "google_places",
                "theme": "poi",
                "source_role": "core_poi_source",
                "path_hint": _raw_path_hint("raw.google.poi"),
                "supports_aoi": True,
                "materialization_scope": "resolved_aoi_clip",
                "materialization_provider": "google_places_fetcher",
                "source_form": "vector",
                "runtime_status": "runtime_candidate",
                "selectable_now": True,
                **track_b_source_metadata("raw.google.poi"),
            },
        ),
        DataSourceNode(
            source_id="raw.rh.poi",
            source_name="RH Points Of Interest",
            supported_types=["dt.raw.vector"],
            disaster_types=list(DEFAULT_DISASTER_TYPES),
            quality_score=0.76,
            source_kind="open_data",
            quality_tier="local_sample",
            freshness_category="sample_snapshot",
            freshness_hours=720,
            freshness_score=0.4,
            supported_job_types=["building", "road", "poi"],
            supported_geometry_types=["point"],
            metadata={
                "kind": "raw_vector",
                "provider_family": "rh",
                "theme": "poi",
                "source_role": "reference_candidate",
                "path_hint": _raw_path_hint("raw.rh.poi"),
                "supports_aoi": False,
                "materialization_scope": "local_only",
                "source_form": "vector",
                "runtime_status": "runtime_candidate",
                "selectable_now": True,
                **track_b_source_metadata("raw.rh.poi"),
            },
        ),
    ]
